### PR TITLE
remove assuming /t:

### PR DESCRIPTION
**Pull request by kewde**
##### Checklist

- [ ] `npm install && npm test` passes
- [ ] tests are included 
- [ ] documentation is changed or added
- [ ] commit message follows [commit guidelines](https://github.com/nodejs/node/blob/master/doc/guides/contributing/pull-requests.md#commit-message-guidelines)

##### Description of change

The assumption that any argument passed to the argv is a target is just plain wrong.
This doesn't allow overwriting anything: breaks `p:/`, `-D` etc..
If you want to add a specific target then just add `/t:`. 

We use this in `node-pre-gyp`, it was working fine for quite a few versions.

### CODE REVIEW

**Comment by bnoordhuis** [comment]
cc @NatalieWolfe - your input is needed.

**Comment by bnoordhuis** [comment]
Also, this conflicts/overlaps with #1540.

**Comment by rvagg** [comment]
Please rebase to master if you'd still like to pursue this.

**Comment by cclauss** [comment]
Too many conflicts.

**Pull request closed without merging**
