### PR TITLE
Adding DCO and CoC

### PR DESCRIPTION
**Pull request by mikeal**

### CODE REVIEW

**Comment by Fishrock123** [comment]
LGTM

**Comment by bnoordhuis** [comment]
@refack No merges, darn it.  As well, did this PR contain up-to-date versions?

**Comment by addaleax** [comment]
> As well, did this PR contain up-to-date versions?

No, of neither document.

**Comment by gibfahn** [comment]
> No merges, darn it

I'd be +1 on reverting back to the previous commit and re-applying it with updated versions. Happy to do it myself if there is agreement.

Also +1 on turning off `Merging` for all the nodejs repos. `Squash and merge` is fine (and the `Rebase and Merge` doesn't particularly cause issues), but merging is just awful.

**Comment by addaleax** [comment]
@gibfahn As far as I can tell, this was either `Squash and Merge` or `Rebase and Merge`; either way, the original Author information was lost.

**Comment by gibfahn** [comment]
It was definitely a normal merge

image

**Comment by addaleax** [comment]
Ah, sorry – I guess I misread this because Github shows the commits ordered by date and this one was so old…

**Comment by refack** [comment]
> @refack No merges, darn it. As well, did this PR contain up-to-date versions?

Ohh, that went horribly wrong 🤦‍♂️
I'll be happy to force push this out.

**Comment by bnoordhuis** [comment]
Yes, let's roll back.

**Comment by refack** [comment]
Done.

**Pull request merged**
