### PR TITLE
Bump gyp 19495aa

### PR DESCRIPTION
**Pull request by refack**
* Bumped `GYP` to latest version
* rebased all floating patched since last bump

##### Checklist

- [x] `npm test` passes
- [x] commit message follows [commit guidelines](https://github.com/nodejs/node/blob/master/CONTRIBUTING.md#commit-guidelines)

##### Affected core subsystem(s)
gyp

### CODE REVIEW

**Comment by refack** [comment]
@joaocgreis PTAL, after we land this we can improve on #1130 (remove `GYP` trickery, and remove COM code in favor of `vswhere`)

**Comment by bnoordhuis** [comment]
@refack Needs a rebase and most likely a new GYP update.

**Comment by refack** [comment]
Ack.
(I'll trade you a bump for a review of https://github.com/nodejs/node/pull/14718)

**Comment by refack** [comment]
* Rebased.
* Bumped `GYP` to https://github.com/refack/GYP/commit/324dd166b7c0b39d513026fa52d6280ac6d56770

* There are 4 other floating patches that are not necessary:
   1. a04ea3051a60bbfdabda3bafef213028cc099f6a - Mostly upstreamed, whats left is https://github.com/nodejs/node-gyp/blob/a04ea3051a60bbfdabda3bafef213028cc099f6a/gyp/pylib/gyp/generator/msvs.py#L341-L342 revered by (3)
   2. ec5fc36a80ea1e98eac1f490545ccb4e71fce846 - Upstreamed
   3. 8a767145c9e34398ca8f2c4c5c9086b0ab79788a - Revert (1)
   4. d6139b538c2219110048ac6e00b5abbe248433db - Upstreamed

**Comment by rvagg** [comment]
🤷‍♂  would be nice to get a sync, but this is too old now

**Pull request closed without merging**
