### PR TITLE
fix: increase node 12 support to ^12.13

### PR DESCRIPTION
**Pull request by lukekarrys**
##### Checklist

- [x] `npm install && npm test` passes
- [x] commit message follows [commit guidelines](https://github.com/googleapis/release-please#how-should-i-write-my-commits)

##### Description of change
`npm@8` updated to `node-gyp@9` which was technically a breaking change for us due to the mismatch of the lower bound of node 12 support. this was done by mistake but we opted not to revert since by the time we noticed we were more concerned that changing node-gyp versions would break more things.

changing the lower bound of node 12 to 12.13 will align with npm 8 and allow us to fix our breaking change without needing to do a bunch of back ports.

Ref https://github.com/nodejs/node-gyp/issues/2753#issuecomment-1332621146
Ref https://github.com/npm/cli/pull/5049#issuecomment-1252911275

### CODE REVIEW

**Comment by lukekarrys** [comment]
#2772 addresses the test failures which are unrelated to the changes in this PR

**Review by ljharb — APPROVED** [review]
<3 thank you

**Comment by lukekarrys** [comment]
@nodejs/node-gyp friendly ping to help this get reviewed. ideally this could get released in [`9.3.1`](https://github.com/nodejs/node-gyp/pull/2775), since i have breaking changes for review in #2770.

**Comment by ljharb** [comment]
@cclauss thanks! how soon do you think a v9 patch release could be cut?

**Pull request merged**
