### PR TITLE
test: upgrade Linux Travis CI to Python 3.8

### PR DESCRIPTION
**Pull request by cclauss**
Blocked by #1921 

Ensure that we remain compatible with the newest version of Python.

##### Checklist

- [ ] `npm install && npm test` passes
- [x] tests are included 
- [ ] documentation is changed or added
- [x] commit message follows [commit guidelines](https://github.com/nodejs/node/blob/master/doc/guides/contributing/pull-requests.md#commit-message-guidelines)

### CODE REVIEW

**Comment by joaocgreis** [comment]
CI: https://ci.nodejs.org/view/All/job/nodegyp-test-pull-request/166/

**Comment by sam-github** [comment]
@cclauss the changes looked ok to me, but travis hit
```
$ pip install flake8
The command "pip install flake8" failed and exited with 127 during .

Your build has been stopped.
/c/Users/travis/.travis/functions: line 109: pip: command not found
```
- https://travis-ci.com/nodejs/node-gyp/jobs/245961156

**Comment by cclauss** [comment]
Yes.  That fix was landed in #1921.  Can someone with Travis admin rights please rerun the tests?

**Comment by joaocgreis** [comment]
@cclauss I've rebased to make it run. But it looks like there's a lot of backlog in Travis...

**Comment by rvagg** [comment]
landed in b91718e

**Pull request closed without merging**
