### PR TITLE
win: improve parsing of SDK version

### PR DESCRIPTION
**Pull request by Loghorn**
##### Checklist
- [x] `npm install && npm test` passes
- [x] commit message follows [commit guidelines](https://github.com/nodejs/node/blob/master/CONTRIBUTING.md#commit-message-guidelines)

##### Description of change
This makes the parsing more robust and fixes the additional issue
related to USB Device Connectivity component.

Fixes: https://github.com/nodejs/node-gyp/issues/1144

### CODE REVIEW

**Comment by joaocgreis** [comment]
cc @refack

**Comment by maclover7** [comment]
CI: https://ci.nodejs.org/job/nodegyp-test-pull-request/82/

**Comment by Loghorn** [comment]
@joaocgreis I've changed the commit message to point to the correct issue (#1466)

**Comment by joaocgreis** [comment]
CI was green, additional run on v0.12 to check the backport to v3.x: https://ci.nodejs.org/job/nodegyp-test-commit/422/ (also green).

Landed in https://github.com/nodejs/node-gyp/commit/25208f12c589c1e5c6b74396b63117685cd55ec6 (`master`) and https://github.com/nodejs/node-gyp/commit/340403ccfe5fcc50ad3c84a29e21fa2939c00c98 (`v3.x`).

Thanks @Loghorn!

**Pull request closed without merging**
