### PR TITLE
chore: Bump tar from 6.1.0 to 6.1.2

### LINKED ISSUE #2473: Security vulnerability: tar
See https://github.com/npm/node-tar/security/advisories/GHSA-3jfq-g458-7qm9

Should be an easy fix to go from `tar@6.1.0` to `tar@6.1.1`. Or is it expected that the users do it themselves since the package.json uses the permissive `^`?

### PR DESCRIPTION
**Pull request by mayank99**
Bumps minimum required version of `tar` from 6.1.0 to 6.1.2. Addresses https://github.com/npm/node-tar/security/advisories/GHSA-3jfq-g458-7qm9 and https://github.com/npm/node-tar/security/advisories/GHSA-r628-mhmh-qjhw

Closes #2473

##### Checklist

- [x] `npm install && npm test` passes
- [ ] documentation is changed or added
- [ ] commit message follows [commit guidelines](https://github.com/googleapis/release-please#how-should-i-write-my-commits)

### CODE REVIEW

**Comment by mayank99** [comment]
@rvagg Publishing this PR. Please let me know if I missed something.

**Comment by rvagg** [comment]
thanks @mayank99 we'll get this out in the coming release (soon)

**Comment by victoria100** [comment]
When are you planing to release this?

**Comment by rvagg** [comment]
yep

**Comment by victoria100** [comment]
When?

**Pull request merged**
