### PR TITLE
Detect visual studio 2017

### PR DESCRIPTION
**Pull request by danielgindi**
This should have been done long ago...

### CODE REVIEW

**Comment by refack** [comment]
@danielgindi thanks for the contribution! 🥇 
As of `node-gyp@3.6.0` detection of VS2017 is already in.
(if you don't have > `v3.6.0` you'll need to update `npm`)

**Comment by danielgindi** [comment]
Actually 3.6.1 is installed, a fresh install - and do not have the VS2017 detection in...
It does use it somehow with an env called `GYP_MSVS_OVERRIDE_PATH`, which does not exist on my system so I have no idea where it comes from.
But on another system - also 3.6.1 just installed fresh - no VS2017 detection...

**Comment by refack** [comment]
> It does use it somehow with an env called GYP_MSVS_OVERRIDE_PATH

https://github.com/nodejs/node-gyp/blob/master/lib/configure.js#L156

We wanted to have VS2017 support before it landed in upstream `GYP` so we "lie" to it to make it work.
If you can't build with `v3.6.1` please supply the error output. Also look if it's related to https://github.com/nodejs/node-gyp/issues/1179

**Comment by danielgindi** [comment]
Okay so I've debugged the `configure.js`, and `findVS2017` says that `"Error: Could not use PowerShell to find VS2017"`
Looking further into it...

**Comment by refack** [comment]
See if this https://github.com/nodejs/node-gyp/pull/1198 helps

**Comment by danielgindi** [comment]
`'Exception calling "Query" with "0" argument(s): "Input string was not in a correct format."\r\nAt line:1 char:95\r\n+ ... e-gyp\\lib\\Find-VS2017.cs\'; [VisualStudioConfiguration.Main]::Query()}\r\n+                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\n    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException\r\n    + FullyQualifiedErrorId : FormatException\r\n \r\n'`

**Comment by danielgindi** [comment]
Yes, #1198 solves it. So we're waiting for v3.6.2, and for it to reach npm upstream...

**Comment by danielgindi** [comment]
Seems like Windows Creators Update has this side effect of making vs2017 harder to detect by the old code.
This really needs to be released soon...

**Comment by refack** [comment]
Will be in `npm@5.0.2`

**Comment by refack** [comment]
Will be in `npm@5.0.2` 
Ref: https://github.com/npm/npm/pull/16894

**Pull request closed without merging**
