### PR TITLE
Release proposal: v8.0.0

### PR DESCRIPTION
**Pull request by rvagg**
I think this needs a dep update. If someone would like to help out on that - go look at https://github.com/npm/cli/blob/latest/package.json and try and match the overlapping semver specifiers to theirs. I tend to keep them roughly in sync to avoid duplication in their releases. Whether or not they'll take a v8.0.0 is another matter, and we may want to recommend they hold off for a little while until this is tested in the wild.

* [[`15a5c7d45b`](https://github.com/nodejs/node-gyp/commit/15a5c7d45b)] - **ci**: migrate deprecated grammar (#2285) (Jiawen Geng) [#2285](https://github.com/nodejs/node-gyp/pull/2285)
* [[`cc1cbce056`](https://github.com/nodejs/node-gyp/commit/cc1cbce056)] - **doc**: update macOS\_Catalina.md (#2293) (iMrLopez) [#2293](https://github.com/nodejs/node-gyp/pull/2293)
* [[`6287118fc4`](https://github.com/nodejs/node-gyp/commit/6287118fc4)] - **doc**: updated README.md to copy easily (#2281) (மனோஜ்குமார் பழனிச்சாமி) [#2281](https://github.com/nodejs/node-gyp/pull/2281)
* [[`66c0f04467`](https://github.com/nodejs/node-gyp/commit/66c0f04467)] - **doc**: add missing `sudo` to Catalina doc (Karl Horky) [#2244](https://github.com/nodejs/node-gyp/pull/2244)
* [[`a78b584236`](https://github.com/nodejs/node-gyp/commit/a78b584236)] - **(SEMVER-MAJOR)** **gyp**: remove support for Python 2 (#2300) (Christian Clauss) [#2300](https://github.com/nodejs/node-gyp/pull/2300)
* [[`c3c510d89e`](https://github.com/nodejs/node-gyp/commit/c3c510d89e)] - **gyp**: update gyp to v0.8.0 (#2318) (Christian Clauss) [#2318](https://github.com/nodejs/node-gyp/pull/2318)
* [[`9e1397c52e`](https://github.com/nodejs/node-gyp/commit/9e1397c52e)] - **(SEMVER-MAJOR)** **gyp**: update gyp to v0.7.0 (#2284) (Jiawen Geng) [#2284](https://github.com/nodejs/node-gyp/pull/2284)
* [[`e81602ef55`](https://github.com/nodejs/node-gyp/commit/e81602ef55)] - **(SEMVER-MAJOR)** **lib**: migrate requests to fetch (#2220) (Matias Lopez) [#2220](https://github.com/nodejs/node-gyp/pull/2220)
* [[`392b7760b4`](https://github.com/nodejs/node-gyp/commit/392b7760b4)] - **lib**: avoid changing process.config (#2322) (Michaël Zasso) [#2322](https://github.com/nodejs/node-gyp/pull/2322)

### CODE REVIEW

**Review by gengjiawen — APPROVED** [review]

**Comment by DeeDeeG** [comment]
Hi. If you get a moment, please take another look at my PR, which is meant to be lumped in with some future semver major bump if landed. v8.0.0 would be a great time to land it, I think.

https://github.com/nodejs/node-gyp/pull/2333

(There was already extensive discussion and a positive review by @cclauss, and some stray comments from other `node-gyp`/`nodejs` folks, and a positive review from a fellow Atom contributor, but no-one else from the core `node-gyp`/`nodejs`team has pressed the "review" button and left their formal review on it other than @cclauss.)

**Comment by DeeDeeG** [comment]
On another note:

> I think this needs a dep update. If someone would like to help out on that - go look at https://github.com/npm/cli/blob/latest/package.json and try and match the overlapping semver specifiers to theirs.

I might be interested in doing this.

**Comment by cclauss** [comment]
@DeeDeeG I agree that #2333 should land in version 8.  Your help on matching the overlapping semver specifiers would be much appreciated.

**Comment by DeeDeeG** [comment]
I took a look at this, and I conclude that any dependency version bumps to "better match `npm`" would be superfluous at this time. (Because `npm`'s and `node-gyp`'s respective dependencies are still in sync enough to 100% dedupe all shared/overlapped dependencies.)

<details>

Here is the diff when making dependencies exactly match `npm` on its `latest` branch (https://github.com/npm/cli/commit/08673c34f0f131619ea8eb75dd325e755bf0a323).

```diff
diff --git a/package.json b/package.json
index 1a4fdf1..a38ecc4 100644
--- a/package.json
+++ b/package.json
@@ -24,13 +24,13 @@
   "dependencies": {
     "env-paths": "^2.2.0",
     "glob": "^7.1.4",
-    "graceful-fs": "^4.2.3",
-    "make-fetch-happen": "^8.0.9",
+    "graceful-fs": "^4.2.6",
+    "make-fetch-happen": "^8.0.14",
     "nopt": "^5.0.0",
-    "npmlog": "^4.1.2",
+    "npmlog": "~4.1.2",
     "rimraf": "^3.0.2",
-    "semver": "^7.3.2",
-    "tar": "^6.0.2",
+    "semver": "^7.3.4",
+    "tar": "^6.1.0",
     "which": "^2.0.2"
   },
   "engines": {
```

There are no major version bumps here. And `node-gyp`'s semver ranges are slightly more generous supersets of `npm`'s. When the proposed v8 of `node-gyp` is included as a dependency of `npm`, every single shared dependency is deduped, no updates necessary at this repo.

For example: `node-gyp`'s dependency range for `graceful-fs` (`^4.2.3`) is a superset of `npm`'s dependency range for the same package `graceful-fs` (`^4.2.6`).

`node-gyp's set: [ 4.2.3, 4.2.4, 4.2.5, npm's set: [ 4.2.6, any future 4.x ] ]`

I would specifically recommend _not_ using tilde `~` semver for `npmlog`, as that would make it _more likely_, not less likely, to become out of sync with `npm` in the future. When a sub-dependency has a looser superset range, in my testing the stricter parent dependency's requirement is used and they are fully deduped. So I believe we would want the looser caret `^` range for `npmlog`, and let `npm` dictate whatever stricter tilde `~` range they desire to lock that package to.

</details>

That said, I could still open a PR to make the semver version ranges more exactly the same if desired.

**Comment by rvagg** [comment]
Excellent work @DeeDeeG! Exactly what I was after. It's clearly not critical but maybe you could open a PR to `master` to adjust our ranges to match (opting for `^` over `~` though).

**Comment by DeeDeeG** [comment]
Just a quick heads-up: I found [a bug](https://github.com/nodejs/node-gyp/issues/2351) in `node-gyp` (or its dependency `gyp`) that's making some packages not build. Not sure if it should block a v8.0.0 release, I leave that to you folks' judgment. (I'm not clear on how many packages are affected vs how many aren't affected, but it's not 100%.)

The issue: https://github.com/nodejs/node-gyp/issues/2351

**Comment by gengjiawen** [comment]
> Hi. If you get a moment, please take another look at my PR, which is meant to be lumped in with some future semver major bump if landed. v8.0.0 would be a great time to land it, I think.
> 
> #2333
> 

#2333 is merged :)

**Comment by rvagg** [comment]
Rebased on master, pulled in:

* [[`0d8a6f1b19`](https://github.com/nodejs/node-gyp/commit/0d8a6f1b19)] - **ci**: update actions/setup-node to v2 (#2302) (Sora Morimoto) [#2302](https://github.com/nodejs/node-gyp/pull/2302)
* [[`a5fd1f41e3`](https://github.com/nodejs/node-gyp/commit/a5fd1f41e3)] - **doc**: add downloads badge (#2352) (Jiawen Geng) [#2352](https://github.com/nodejs/node-gyp/pull/2352)
* [[`1bd18f3e77`](https://github.com/nodejs/node-gyp/commit/1bd18f3e77)] - **(SEMVER-MAJOR)** **lib**: drop Python 2 support in find-python.js (#2333) (DeeDeeG) [#2333](https://github.com/nodejs/node-gyp/pull/2333)

Any final objections to moving forward to a release @cclauss @gengjiawen @richardlau?

**Comment by rvagg** [comment]
Added

* [[`06ddde27f9`](https://github.com/nodejs/node-gyp/commit/06ddde27f9)] - **deps**: sync mutual dependencies with npm (DeeDeeG) [#2348](https://github.com/nodejs/node-gyp/pull/2348)

**Comment by gengjiawen** [comment]
> Rebased on master, pulled in:
> 
> * [[`0d8a6f1b19`](https://github.com/nodejs/node-gyp/commit/0d8a6f1b19)] - **ci**: update actions/setup-node to v2 (#2302) (Sora Morimoto) [#2302](https://github.com/nodejs/node-gyp/pull/2302)
> * [[`a5fd1f41e3`](https://github.com/nodejs/node-gyp/commit/a5fd1f41e3)] - **doc**: add downloads badge (#2352) (Jiawen Geng) [#2352](https://github.com/nodejs/node-gyp/pull/2352)
> * [[`1bd18f3e77`](https://github.com/nodejs/node-gyp/commit/1bd18f3e77)] - **(SEMVER-MAJOR)** **lib**: drop Python 2 support in find-python.js (#2333) (DeeDeeG) [#2333](https://github.com/nodejs/node-gyp/pull/2333)
> 
> Any final objections to moving forward to a release @cclauss @gengjiawen @richardlau?

Let's do it.

**Review by cclauss — APPROVED** [review]
Let’s do it!

**Review by richardlau — APPROVED** [review]

**Comment by DeeDeeG** [comment]
If I might request that `gyp` (`gyp-next`) be bumped to 0.8.1, that fixes a big part of https://github.com/nodejs/node-gyp/issues/2351.

That issue affects some `macOS` packages 100% of the time, including a few we use when building the Atom text editor. We wouldn't be able to build Atom with `node-gyp` 8.0.0 on macOS.

The issue title is a bit misleading. Yes, the file only errors out when it's run with Python less than 3.6... But it will _Always_ run on Python 2 on macOS. Every copy of macOS ships with Python 2, and the version of Python being run is determined by a shebang line `#!/usr/bin/env python`. The sophisticated Python detection in `lib/find-python.js` is not applicable here, and so this `node-gyp` 8.0.0 release simply won't build certain packages on macOS.

Bumping to `gyp-next` 0.8.1 at least has better shebang lines. `#!/usr/bin/env python3`. I have proposed a more thorough fix in that issue, but the basic idea of "let's run this Python 3-only file with Python 3" seems like a good idea. If that sounds agreeable, then I can recommend to bump `gyp` to 0.8.1 to ensure the file is run with Python 3. Thanks for considering.

**Comment by rvagg** [comment]
pulled in

* [[`0da2e0140d`](https://github.com/nodejs/node-gyp/commit/0da2e0140d)] - **gyp**: update gyp to v0.8.1 (#2355) DeeDeeG) [#2355](https://github.com/nodejs/node-gyp/pull/2355)
* [[`0093ec8646`](https://github.com/nodejs/node-gyp/commit/0093ec8646)] - **gyp**: Improve our flake8 linting tests (Christian Clauss) [#2356](https://github.com/nodejs/node-gyp/pull/2356)

**Comment by rvagg** [comment]
v8.0.0 released, thanks all

**Pull request merged**
