### PR TITLE
Travis CI: Add the long dead Python 2.6

### PR DESCRIPTION
**Pull request by cclauss**
##### Checklist

- [ ] `npm install && npm test` passes
- [x] tests are included 
- [ ] documentation is changed or added
- [ ] commit message follows [commit guidelines](https://github.com/nodejs/node/blob/master/doc/guides/contributing/pull-requests.md#commit-message-guidelines)

##### Description of change

As discussed in #1912, we need to test software that we claim to support.

### CODE REVIEW

**Comment by rvagg** [comment]
remade the branch and cherry-picked the HEAD commit onto it so it's properly on v5.x now, will watch Travis to see what it says, regardless I don't think this is (a) needed or (b) requires us to document it, it's just not something we can change on v5.x because it's been baked in already.

**Comment by cclauss** [comment]
I rebased on v5.x at same time you did so who knows what we got.  Let’s see what Travis says.  If it fails then I believe our release notes should reflect that.

**Comment by cclauss** [comment]
Flake8 no longer supports Python 2.6 but even when flake8 is fully disabled, the Py26 run fails.

**Comment by rvagg** [comment]
it failed because it's running Node 0.10 on that image, I switched to 10 (`nvm install 10`), but then it failed because it didn't have `semverRange`, so I rebased onto rvagg/restore-python-2.6, but then it's failing because the compilers is too old on precise: https://travis-ci.com/nodejs/node-gyp/jobs/242023105, but that's a pretty good sign that it actually works, or at least it's not failing because of Python 2.6, it's making the build resources so getting cleanly through `gyp`. Would be interesting to figure out how to make this run. Can we do 2.6 on a newer image than precise?

**Comment by cclauss** [comment]
Try upgrading to __trusty__

**Comment by rvagg** [comment]
green with trusty 👍 will merge this into v5.x

**Comment by rvagg** [comment]
No, I won't add this, because it disables flake8 for everything, we'll need to differentiate before it can land. I've cleaned it up into a single commit on top of the current v5.x and force pushed it up.

**Pull request closed without merging**
