### PR TITLE
update gyp to b3cef02

### PR DESCRIPTION
**Pull request by iWuzHere**
Includes two patches for AIX. Adds support for both 32-bit and 64-bit
files[0] and uses -RPf for cp instead of -af (which is unsupported)[1]

[0] https://codereview.chromium.org/1319663007
[1] https://codereview.chromium.org/1368133002

CI run here https://ci.nodejs.org/job/node-test-commit/882/
Intermittent failure that passed on rerun:
https://ci.nodejs.org/job/node-test-commit-arm/958/

### CODE REVIEW

**Comment by iWuzHere** [comment]
Note this also removes support for android as gyp has abandoned it. If you still want to keep android support in the code I can just pull the two AIX changes

**Comment by mhdawson** [comment]
@bnoordhuis  can you take a look at this one

**Comment by mhdawson** [comment]
@bnoordhuis, there were 2 PRs to update gyp if you can also look at this one it would be great.

@shigeki, since you commented on the other one giving you an FYI here as well

**Comment by shigeki** [comment]
FYI: Currently, a floating patch of https://github.com/nodejs/node/commit/58e914f9bc866fe424aa38b5e9ac42e6216d5f30 is applied to tools/gyp in node so as to avoid a build error occured in MacOS without XCode.  Ben has already submitted the patch to upstream in https://codereview.chromium.org/1213123002/ but it's not fixed yet. 
The patch is needed to work in CI where only command line tools are installed but XCode is not.
I think it is a very limited environments and I'm not sure how much it is affected in using node-gyp.

**Comment by bnoordhuis** [comment]
@iWuzHere Before I start reviewing this: node-gyp's copy of gyp was floating a few patches of its own.  Did you preserve those?

**Comment by iWuzHere** [comment]
I have added the floating patches.

**Comment by bnoordhuis** [comment]
I think you're missing nodejs/node-gyp@39a06bc.

**Comment by iWuzHere** [comment]
I shouldn't easy_xml.py hasnt changed in https://github.com/iWuzHere/node-gyp/commit/2f1d5efa1c747b1c0c7d5d721b25942d283606f9

**Comment by bnoordhuis** [comment]
LGTM but can you update the commit log with a quick overview of changes/additions?

**Comment by iWuzHere** [comment]
I have updated the commit message

**Comment by bnoordhuis** [comment]
Thanks, landed in f5d86eb...9049241.

@rvagg @TooTallNate Maybe one of you can do a release for this?

**Comment by mhdawson** [comment]
@bnoordhuis when you say to a release is that how it gets pulled into the dependencies within Node itself  ?

**Comment by bnoordhuis** [comment]
Sadly, no.  The chain of releases is node-gyp -> npm -> node.

**Pull request closed without merging**
