### PR TITLE
Migration from tap to mocha

### PR DESCRIPTION
**Pull request by StefanStojanovic**
##### Checklist
- [x] `npm install && npm test` passes
- [x] tests are included
- [x] commit message follows [commit guidelines](https://github.com/googleapis/release-please#how-should-i-write-my-commits)

##### Description of change
After the `make-fetch-happen` update in https://github.com/nodejs/node-gyp/commit/02480f6b6894a6bb81dd3e1365bc4df6d5336f7c, GitHub Actions started failing. Migrating from `tap` to `mocha` testing framework as issues only happened in GitHub Actions (tested locally with various node/python combinations, didn't reproduce any failures). This PR is made based on investigation and work done in https://github.com/nodejs/node-gyp/pull/2837 as the simplest and probably the cleanest solution. With these changes, `Mocha` replaces `tap` completely, thus restoring GitHub Actions stability.

### CODE REVIEW

**Comment by StefanStojanovic** [comment]
Thanks for that information. I didn't want to rewrite tests initially as I did not know if that is the direction we want to go in. Since it is, I'll change the tests as well.

**Comment by StefanStojanovic** [comment]
@dennisameling and @dsanders11 when you get time, please review the changes I made to the tests you added in https://github.com/nodejs/node-gyp/pull/2650 and https://github.com/nodejs/node-gyp/pull/2846 respectively. They were supposed to be just changed from `tap` to `mocha`, but if I made some other unintended change let me know.

**Comment by dsanders11** [comment]
@StefanStojanovic, parallel install tests refactor to `mocha` LGTM.

**Comment by dennisameling** [comment]
Refactor of the VS2022 tests LGTM ✅️ thank you!

**Comment by cclauss** [comment]
Will we do a similar migration in the testing of Node.js?
* https://github.com/search?q=repo%3Anodejs%2Fnode+%22+tap%22&type=code

Will we be able to drop `tap2junit`?
* https://github.com/nodejs/tap2junit --> https://pypi.org/project/tap2junit

**Comment by rvagg** [comment]
so for background: tap2junit is used for nice test feedback in jenkins - you can run these tests in ci.nodejs.org and get nice output

mocha can do tap output if you want, but none of this is essential, it could all be ditched I think and just get nice mocha output :shrug:

**Comment by StefanStojanovic** [comment]
> Will we do a similar migration in the testing of Node.js?

There is no plan to do that for Node.js tests as they are working well.

> Will we be able to drop `tap2junit`?

These tests are run through GitHub Actions, `tap2junit` is not used here.

**Comment by rvagg** [comment]
> These tests are run through GitHub Actions, tap2junit is not used here.

See https://ci.nodejs.org/view/All/search/?q=gyp

**Comment by cclauss** [comment]
Should these changes be landed on https://github.com/nodejs/gyp-next first?

**Comment by StefanStojanovic** [comment]
> See https://ci.nodejs.org/view/All/search/?q=gyp

Are those jobs still in use? They seem outdated and have no build history. Also, I've only seen GitHub Actions in node-gyp repo PRs

> Should these changes be landed on https://github.com/nodejs/gyp-next first?

I do not know what you mean by this, since these changes change node-gyp tests. From what I saw (went through it very briefly) gyp-next has a `node-gyp integration` workflow that runs node-gyp tests (and for that reason is in red lately), but it uses this repo, so landing this PR here should manifest there as well. If you had something else in mind please let me know.

**Comment by rvagg** [comment]
https://ci.nodejs.org/job/nodegyp-test-pull-request/

One of the benefits of this is the ability to test a broader range of Node versions and platform permutations than CI allows; which is helpful for a project that depends so much on OS-level inputs like node-gyp does. It hasn't been used much recently because the people that might have used it have slowly faded away, leaving us with CI.
I'm not suggesting it be retained as an important piece of functionality, or block the work here, just maybe not forgotten as a thing of value to maybe utilise or integrate in the CI process at some point.

**Comment by StefanStojanovic** [comment]
Since we've been discussing this PR for some time, and I see no clear objections to the proposed changes, I just wanted to ask if there's something else I should do to get it approved.

**Pull request merged**
