### PR TITLE
feat: remove support for VS2015 in Node.js >=19

### PR DESCRIPTION
**Pull request by targos**
Refs: https://github.com/nodejs/node/issues/37472

### CODE REVIEW

**Comment by targos** [comment]
/cc @nodejs/build @nodejs/npm @nodejs/releasers

We will need to coordinate an npm release with this change, its inclusion in v19.0.0, and adaptations to the Node.js CI.

**Comment by targos** [comment]
I think this is something we should do regardless of issues with V8, to prepare users for Node.js 20. Visual Studio 2015 will be out of support on [Oct 14, 2025](https://learn.microsoft.com/en-us/lifecycle/products/visual-studio-2015), before the 20.x EoL.

**Review by sxa — APPROVED** [review]

**Review by Trott — APPROVED** [review]

**Review by richardlau — APPROVED** [review]
LGTM but I wonder if the commit message should mark this as a breaking change (we're using conventional commits for release-please).

**Comment by targos** [comment]
I thought about it but since it only applies to an unreleased version of node, I thought it could not really break anyone

**Comment by targos** [comment]
But feel free to land as breaking, I have no strong opinion on that

**Comment by richardlau** [comment]
Ah good point about it referring to an unreleased version. I'm okay with it landing just as a feat (i.e. Node.js 19 support).

**Review by gengjiawen — APPROVED** [review]

**Pull request merged**
