### PR TITLE
add msvs 2017 support

### PR DESCRIPTION
**Pull request by dothebart**

### CODE REVIEW

**Comment by richardlau** [comment]
Based on https://github.com/nodejs/node-gyp/pull/1952#issuecomment-549631126 this isn't necessary? cc @joaocgreis

**Comment by dothebart** [comment]
after opening the PR I saw that these changes already there in GYP3. However, as long as you use the node-gyp this is needed.

**Comment by joaocgreis** [comment]
This shouldn't be needed, VS detection is not done by GYP but in https://github.com/nodejs/node-gyp/blob/master/lib/find-visualstudio.js.

@dothebart what issue did you see that needs this? Is the detection in node-gyp not working for you? Can you paste the output of a failing `node-gyp rebuild --verbose` here?

**Comment by dothebart** [comment]
Ah, I don't compile V8 for nodejs - its https://github.com/ArangoDB/ArangoDB - so I don't have this file.
I now continued with gyp3, which has this. So if you don't want it, close it.

**Comment by joaocgreis** [comment]
I guess we'll have to land something like this or remove autodetection from the GYP side, but I'd rather wait until we figure out how GYP will be managed here. @dothebart thanks for opening this PR and trying to help.

**Comment by dothebart** [comment]
hm, asking a heretic question - how do you run `.js` before having a ready compiled V8?

**Comment by joaocgreis** [comment]
I'm not sure I understand your question... Here in node-gyp, Node.js is required to run, so V8 is always already compiled.

For compiling Node.js itself in https://github.com/nodejs/node/ a different mechanism is used. It uses `vswhere` from the command line: https://github.com/nodejs/node/blob/ed401236f6988c6ad62a21dbbf808da83782bee0/vcbuild.bat#L247

**Comment by dothebart** [comment]
ah, nice. a shellscript to tell the environment autodetection infrastructure about the infrastructure to work around the autodetection. 
Is Gyp3 the way ahead?

**Comment by joaocgreis** [comment]
There's discussion about the way forward in https://github.com/nodejs/node-gyp/issues/1791. There was a PR to change to GYP3 https://github.com/nodejs/node-gyp/pull/1845 but it was closed. From what I see, it looks like we'll be maintaining GYP here specifically to be used in node-gyp at least for a while.

**Pull request closed without merging**
