### PR TITLE
Update link of gyp as Google code is shutting down

### PR DESCRIPTION
**Pull request by PeterDaveHello**

### CODE REVIEW

**Comment by gibfahn** [comment]
Would https://chromium.googlesource.com/external/gyp or https://gyp.gsrc.io/ be a better starting point for someone who doesn't know what gyp is?

**Comment by PeterDaveHello** [comment]
Oh cool, would you like me to update it?

**Comment by gibfahn** [comment]
@PeterDaveHello Yes, sounds good to me. I guess you should use https://gyp.gsrc.io as that seems to be the homepage.

**Comment by PeterDaveHello** [comment]
@gibfahn thanks, if you don't mind, I just directly updated and committed on GitHub, I think you can squash them directly on GitHub, too, if you don't like it, I can clone and squash them locally or just send a new one, thanks.

**Comment by gibfahn** [comment]
@PeterDaveHello looks fine to me. This needs a `node-gyp` contributor to review though.

**Comment by bnoordhuis** [comment]
Thanks Peter, landed in ff9a6fa.

**Pull request closed without merging**
