### PR TITLE
test: GitHub Actions add Windows to the testing

### PR DESCRIPTION
**Pull request by cclauss**
@joaocgreis This might be of interest to you.

##### Checklist

- [ ] `npm install && npm test` passes
- [x] tests are included 
- [ ] documentation is changed or added
- [x] commit message follows [commit guidelines](https://github.com/nodejs/node/blob/master/doc/guides/contributing/pull-requests.md#commit-message-guidelines)

### CODE REVIEW

**Comment by cclauss** [comment]
Yes.  I am not a Windows guy and I do not understand how to fix __ test_BinaryNamesWindows()__
https://github.com/nodejs/node-gyp/pull/1996/checks?check_run_id=350074778#step:6:23

**Comment by joaocgreis** [comment]
@cclauss isn't this similar to what happened in Travis, the VS version is more recent than the one supported by our gyp version? If this is the case, a good way to fix is to set the MSVS variables similarly to Travis: https://github.com/nodejs/node-gyp/blob/5a729e86eef11c018d40faa21be1120debe59950/.travis.yml#L106

**Comment by cclauss** [comment]
[Powershell](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#using-a-specific-shell) says [_The term 'GYP_MSVS_VERSION=2015' is not recognized as the name of a cmdlet, function, script file, or operable program._](https://github.com/nodejs/node-gyp/pull/1996/checks?check_run_id=366587786#step:7:6)

**Comment by cclauss** [comment]
@joaocgreis Using __shell: bash__ along with your suggestion enables the Windows tests to pass.  Thanks much!

**Pull request merged**
