### PR TITLE
v5.0.0 proposal

### PR DESCRIPTION
**Pull request by rvagg**
This is what a v5.0.0 would look like, can we get this right and clean up the backlog on `master` out of the door? This is a WIP, I haven't reviewed much of what's in here and can't vouch for its reliability or stability.

@cclauss @refack what does Python 3 support look like at the moment? Are we there yet?

_(updated with latest)_

* [[`81f3a92338`](https://github.com/nodejs/node-gyp/commit/81f3a92338)] - Update list of Node.js versions to test against. (Ben Noordhuis) [#1670](https://github.com/nodejs/node-gyp/pull/1670)
* [[`4748f6ab75`](https://github.com/nodejs/node-gyp/commit/4748f6ab75)] - Remove deprecated compatibility code. (Ben Noordhuis) [#1670](https://github.com/nodejs/node-gyp/pull/1670)
* [[`45e3221fd4`](https://github.com/nodejs/node-gyp/commit/45e3221fd4)] - Remove an outdated workaround for Python 2.4 (cclauss) [#1650](https://github.com/nodejs/node-gyp/pull/1650)
* [[`721dc7d314`](https://github.com/nodejs/node-gyp/commit/721dc7d314)] - Add ARM64 to MSBuild /Platform logic (Jon Kunkee) [#1655](https://github.com/nodejs/node-gyp/pull/1655)
* [[`a5b7410497`](https://github.com/nodejs/node-gyp/commit/a5b7410497)] - Add ESLint no-unused-vars rule (Jon Moss) [#1497](https://github.com/nodejs/node-gyp/pull/1497)
* [[`8a83972743`](https://github.com/nodejs/node-gyp/commit/8a83972743)] - **(SEMVER-MAJOR)** **bin**: follow XDG OS conventions for storing data (Selwyn) [#1570](https://github.com/nodejs/node-gyp/pull/1570)
* [[`9e46872ea3`](https://github.com/nodejs/node-gyp/commit/9e46872ea3)] - **bin,lib**: remove extra comments/lines/spaces (Jon Moss) [#1508](https://github.com/nodejs/node-gyp/pull/1508)
* [[`8098ebdeb4`](https://github.com/nodejs/node-gyp/commit/8098ebdeb4)] - **deps**: replace `osenv` dependency with native `os` (Selwyn)
* [[`f83b457e03`](https://github.com/nodejs/node-gyp/commit/f83b457e03)] - **deps**: bump request to 2.8.7, fixes heok/hawk issues (Rohit Hazra) [#1492](https://github.com/nodejs/node-gyp/pull/1492)
* [[`323cee7323`](https://github.com/nodejs/node-gyp/commit/323cee7323)] - **deps**: pin `request` version range (Refael Ackermann) [#1300](https://github.com/nodejs/node-gyp/pull/1300)
* [[`c515912d08`](https://github.com/nodejs/node-gyp/commit/c515912d08)] - **doc**: improve issue template (Bartosz Sosnowski) [#1618](https://github.com/nodejs/node-gyp/pull/1618)
* [[`cca2d66727`](https://github.com/nodejs/node-gyp/commit/cca2d66727)] - **doc**: python info needs own header (Taylor D. Lee) [#1245](https://github.com/nodejs/node-gyp/pull/1245)
* [[`3e64c780f5`](https://github.com/nodejs/node-gyp/commit/3e64c780f5)] - **doc**: lint README.md (Jon Moss) [#1498](https://github.com/nodejs/node-gyp/pull/1498)
* [[`a20faedc91`](https://github.com/nodejs/node-gyp/commit/a20faedc91)] - **(SEMVER-MAJOR)** **gyp**: enable MARMASM items only on new VS versions (João Reis) [#1762](https://github.com/nodejs/node-gyp/pull/1762)
* [[`721eb691cf`](https://github.com/nodejs/node-gyp/commit/721eb691cf)] - **gyp**: teach MSVS generator about MARMASM Items (Jon Kunkee) [#1679](https://github.com/nodejs/node-gyp/pull/1679)
* [[`91744bfecc`](https://github.com/nodejs/node-gyp/commit/91744bfecc)] - **gyp**: add support for Windows on Arm (Richard Townsend) [#1739](https://github.com/nodejs/node-gyp/pull/1739)
* [[`a6e0a6c7ed`](https://github.com/nodejs/node-gyp/commit/a6e0a6c7ed)] - **gyp**: move compile\_commands\_json (Paul Maréchal) [#1661](https://github.com/nodejs/node-gyp/pull/1661)
* [[`92e8b52cee`](https://github.com/nodejs/node-gyp/commit/92e8b52cee)] - **gyp**: fix target --\> self.target (cclauss)
* [[`febdfa2137`](https://github.com/nodejs/node-gyp/commit/febdfa2137)] - **gyp**: fix sntex error (cclauss) [#1333](https://github.com/nodejs/node-gyp/pull/1333)
* [[`588d333c14`](https://github.com/nodejs/node-gyp/commit/588d333c14)] - **gyp**: \_winreg module was renamed to winreg in Python 3. (Craig Rodrigues)
* [[`98226d198c`](https://github.com/nodejs/node-gyp/commit/98226d198c)] - **gyp**: replace basestring with str, but only on Python 3. (Craig Rodrigues)
* [[`7535e4478e`](https://github.com/nodejs/node-gyp/commit/7535e4478e)] - **gyp**: replace deprecated functions (Craig Rodrigues)
* [[`2040cd21cc`](https://github.com/nodejs/node-gyp/commit/2040cd21cc)] - **gyp**: use print as a function, as specified in PEP 3105. (Craig Rodrigues)
* [[`abef93ded5`](https://github.com/nodejs/node-gyp/commit/abef93ded5)] - **gyp**: get ready for python 3 (cclauss)
* [[`43031fadcb`](https://github.com/nodejs/node-gyp/commit/43031fadcb)] - **python**: clean-up detection (João Reis) [#1582](https://github.com/nodejs/node-gyp/pull/1582)
* [[`49ab79d221`](https://github.com/nodejs/node-gyp/commit/49ab79d221)] - **python**: more informative error (Refael Ackermann) [#1269](https://github.com/nodejs/node-gyp/pull/1269)
* [[`997bc3c748`](https://github.com/nodejs/node-gyp/commit/997bc3c748)] - **readme**: add ARM64 info to MSVC setup instructions (Jon Kunkee) [#1655](https://github.com/nodejs/node-gyp/pull/1655)
* [[`788e767179`](https://github.com/nodejs/node-gyp/commit/788e767179)] - **test**: remove unused variable (João Reis)
* [[`6f5a408934`](https://github.com/nodejs/node-gyp/commit/6f5a408934)] - **tools**: fix usage of inherited -fPIC and -fPIE (Jens) [#1340](https://github.com/nodejs/node-gyp/pull/1340)
* [[`0efb8fb34b`](https://github.com/nodejs/node-gyp/commit/0efb8fb34b)] - **(SEMVER-MAJOR)** **win**: support running in VS Command Prompt (João Reis) [#1762](https://github.com/nodejs/node-gyp/pull/1762)
* [[`360ddbdf3a`](https://github.com/nodejs/node-gyp/commit/360ddbdf3a)] - **(SEMVER-MAJOR)** **win**: add support for Visual Studio 2019 (João Reis) [#1762](https://github.com/nodejs/node-gyp/pull/1762)
* [[`8f43f68275`](https://github.com/nodejs/node-gyp/commit/8f43f68275)] - **(SEMVER-MAJOR)** **win**: detect all VS versions in node-gyp (João Reis) [#1762](https://github.com/nodejs/node-gyp/pull/1762)
* [[`7fe4095974`](https://github.com/nodejs/node-gyp/commit/7fe4095974)] - **(SEMVER-MAJOR)** **win**: generic Visual Studio 2017 detection (João Reis) [#1762](https://github.com/nodejs/node-gyp/pull/1762)
* [[`7a71d68bce`](https://github.com/nodejs/node-gyp/commit/7a71d68bce)] - **win**: use msbuild from the configure stage (Bartosz Sosnowski) [#1654](https://github.com/nodejs/node-gyp/pull/1654)
* [[`d3b21220a0`](https://github.com/nodejs/node-gyp/commit/d3b21220a0)] - **win**: fix delay-load hook for electron 4 (Andy Dill)

### CODE REVIEW

**Comment by refack** [comment]
BTW this could be 4.0.0...

Python3 is close, Only thing that's known to be broken is cross-compilation, but I need a better CI environment to test the fix.

**Comment by rvagg** [comment]
> BTW this could be 4.0.0...

No, I just released 4.0.0 based on your 3.x proposal, that last release was semver-major so I just did the full bump

**Comment by cclauss** [comment]
Agreed but could you please unpack __a better CI environment__ for us?  What exactly is needed?

**Comment by refack** [comment]
> No, I just released 4.0.0 based on your 3.x proposal,

Ok. My main concern is/was coordination with `npm`...

> a better CI environment

Currently GYP3 and `node-gyp` run on a limited set of platforms, i.e. what is available on free CI services; Windows, Ubuntu, and macOS over Intel x64.

IMHO a better testing environment would be the Node.js build cluster.

**Comment by joaocgreis** [comment]
@rvagg can you include https://github.com/nodejs/node-gyp/pull/1679 and https://github.com/nodejs/node-gyp/pull/1739? Both just landed in master, thanks!

**Comment by Stanzilla** [comment]
missing visual studio 2019 support which should be prioritized.

**Comment by jkunkee** [comment]
> @rvagg can you include #1679 and #1739? Both just landed in master, thanks!

#1739 is the last Node.js-ish change necessary for Electron v6 to ship with ARM64 Windows support, so I'm particularly interested in seeing it land in an official node-gyp release. (Right now they have to manually patch node-gyp to HEAD to get builds out.)

**Comment by cclauss** [comment]
Does this repo have any automated testing?  I am reluctant to endorse a release that is not supported by at least some level of automated testing.  With 225 days until the end of life of Python 2, I still see several calls to functionality that no longer exists in Python 3.  Some basic linting would really help.

**Comment by rvagg** [comment]
Re testing: @cclauss we have a ci.nodejs.org job that can be triggered manually, not automatic yet but I think that should be doable with the github-bot setup.

Re 5.0.0: folks, how about we aim to get a 5.0.0 out within the next month, we can be ambitious with what's included but at the same time recommend to npm that they _not_ pick it up as the default version straight away. That would alleviate some of the pressure to get this perfect but we'd still get it in the hands of a large number of people that are using it directly—and we can dogfood it ourselves.

Does that sound like a reasonable strategy? I'm struggling to come up with a better idea for moving forward here.

**Comment by Stanzilla** [comment]
@rvagg it's still open if 5.0 will include the move to python3, right?

**Comment by cclauss** [comment]
Some of the __Python 3__ issues that need to be addressed...

[flake8](http://flake8.pycqa.org) testing of https://github.com/nodejs/node-gyp on Python 3.7.1

$ __flake8 . --count --select=E9,F63,F72,F82 --show-source --statistics__
```
./gyp/tools/pretty_vcproj.py:31:12: F821 undefined name 'cmp'
    return cmp(x[0], y[0])
           ^
./gyp/tools/pretty_vcproj.py:59:12: F821 undefined name 'cmp'
    return cmp(get_string(x), get_string(y))
           ^
./gyp/pylib/gyp/MSVSVersion.py:189:18: F821 undefined name '_winreg'
    with OpenKey(_winreg.HKEY_LOCAL_MACHINE, subkey) as hkey:
                 ^
./gyp/pylib/gyp/input.py:1185:10: F632 use ==/!= to compare str, bytes, and int literals
      if the_dict_key is 'variables' and variable_name in the_dict:
         ^
./gyp/pylib/gyp/xcode_emulation.py:847:9: F821 undefined name 'cflags'
        cflags.append('-F' + platform_root + '/Developer/Library/Frameworks/')
        ^
./gyp/pylib/gyp/MSVSNew.py:55:12: F821 undefined name 'cmp'
    return cmp((self.name, self.get_guid()), (other.name, other.get_guid()))
           ^
./gyp/pylib/gyp/simple_copy.py:31:28: F821 undefined name 'long'
for x in (type(None), int, long, float,
                           ^
./gyp/pylib/gyp/simple_copy.py:32:22: F821 undefined name 'unicode'
          bool, str, unicode, type):
                     ^
./gyp/pylib/gyp/xcodeproj_file.py:327:56: F821 undefined name 'unicode'
      elif isinstance(value, str) or isinstance(value, unicode) or \
                                                       ^
./gyp/pylib/gyp/xcodeproj_file.py:606:28: F821 undefined name 'unicode'
    elif isinstance(value, unicode):
                           ^
./gyp/pylib/gyp/xcodeproj_file.py:769:37: F821 undefined name 'unicode'
             not (item.__class__ == unicode and property_type == str):
                                    ^
./gyp/pylib/gyp/xcodeproj_file.py:777:36: F821 undefined name 'unicode'
           not (value.__class__ == unicode and property_type == str):
                                   ^
./gyp/pylib/gyp/xcodeproj_file.py:791:58: F821 undefined name 'unicode'
        elif isinstance(value, str) or isinstance(value, unicode) or \
                                                         ^
./gyp/pylib/gyp/xcodeproj_file.py:1019:14: F821 undefined name 'cmp'
      return cmp(self.Name(), other.Name())
             ^
./gyp/pylib/gyp/xcodeproj_file.py:2736:18: F821 undefined name 'cmp'
                 cmp(x['ProjectRef'].Name().lower(),
                 ^
./gyp/pylib/gyp/xcodeproj_file.py:2845:14: F821 undefined name 'cmp'
      return cmp(x_index, y_index)
             ^
./gyp/pylib/gyp/xcodeproj_file.py:2893:52: F821 undefined name 'cmp'
                                  cmp=lambda x, y: cmp(x, y)):
                                                   ^
./gyp/pylib/gyp/xcodeproj_file.py:2920:45: F821 undefined name 'cmp'
                           cmp=lambda x, y: cmp(x.id, y.id)):
                                            ^
./test/fixtures/test-charmap.py:5:1: F821 undefined name 'reload'
reload(sys)
^
1     F632 use ==/!= to compare str, bytes, and int literals
18    F821 undefined name 'cmp'
19
```
__E901,E999,F821,F822,F823__ are the "_showstopper_" [flake8](http://flake8.pycqa.org) issues that can halt the runtime with a SyntaxError, NameError, etc. These 5 are different from most other flake8 issues which are merely "style violations" -- useful for readability but they do not effect runtime safety.
* F821: undefined name `name`
* F822: undefined name `name` in `__all__`
* F823: local variable name referenced before assignment
* E901: SyntaxError or IndentationError
* E999: SyntaxError -- failed to compile a file into an Abstract Syntax Tree

**Comment by joaocgreis** [comment]
@rvagg https://github.com/nodejs/node-gyp/pull/1762 just landed, it would be great if you can include it (essentially, all of master).

The strategy of just making the release and recommending to npm to not pick it up as default right away sounds like the best path forward to me. We just have to be prepared to release a fix quickly if any issue is actually found.

I'd rather see a v5.0.0 come out quickly because of https://github.com/nodejs/node-gyp/issues/1764. I don't see a reason to wait for Python 3 support, we can release v6.0.0 as soon as it's ready. It's even probably better to have it in its own release. Let me know if I can help with the release, thanks!

**Comment by rvagg** [comment]
I've done a rebase and made a new CHANGELOG, it's in OP. Any blockers for pushing this out? If not, maybe we should do it tomorrow?

Again, let's not recommend npm pick this one up straight away but let's also get back onto a more regular cadence of releases and not let these things back up so much. Python 3 support seems like the top priority after this. We're not constrained by major version bump cadence but we should be prepared to go back and fix older majors for folks that really need things fixed but can't afford the breakage, LTS-style.

**Comment by rvagg** [comment]
Published v5.0.0.

@refack or @joaocgreis do either of you have a login to the new npm bug tracker? We can't open issues on the repo anymore. We need to let them know not to pick this one up until we have a patch or minor release or two and that we can continue to patch 4.x if there are critical bugs. I thought about opening a PR to do it but that'd be a bit too obnoxious I think.

**Comment by joaocgreis** [comment]
Thanks @rvagg!

I opened this in npm: https://npm.community/t/node-gyp-v5-0-0-released/8179

**Pull request closed without merging**
