### PR TITLE
fix spelling in gyp

### PR DESCRIPTION
**Pull request by bipin000**
##### Checklist

- [x] `npm install && npm test` passes
- [x] tests are included 
- [x] documentation is changed or added
- [x] commit message follows [commit guidelines](https://github.com/nodejs/node/blob/master/CONTRIBUTING.md#commit-message-guidelines)

### CODE REVIEW

**Comment by gibfahn** [comment]
@bipin000 thanks for the PR

At the moment your commit is authored by:

So at the moment your Git author name and email address are set to:

```
bct <bipin.tripathi@ocharge.co.ke>
```

People usually choose to use their full names for commits. To set your name globally you can do:

```bash
git config --global user.name "Bipin Tripathi"
git config --global user.email "bipin.tripathi@ocharge.co.ke"
```

To change the author for a single commit you can do:

```bash
git commit --amend --author="Bipin Tripathi <bipin.tripathi@ocharge.co.ke>"
git push --force-with-lease
```

If you don't want to have your name against this commit, that's fine too.

**Comment by gibfahn** [comment]
Also it looks like your email isn't associated with your GitHub ID, which means GitHub won't credit you for the commit. To fix this go to https://github.com/settings/emails and add `bipin.tripathi@ocharge.co.ke`.

**Comment by gibfahn** [comment]
Same comment as https://github.com/nodejs/node/pull/16633#issuecomment-340785388p, could you upstream this first?

**Comment by bipin000** [comment]
@gibfahn thanks !! I have updated the email

**Pull request closed without merging**
