### PR TITLE
lib: enable support for zoslib on z/OS

### PR DESCRIPTION
**Pull request by alexcfyung**
##### Checklist

- [x] `npm install && npm test` passes
- [ ] tests are included 
- [ ] documentation is changed or added
- [x] commit message follows [commit guidelines](https://github.com/googleapis/release-please#how-should-i-write-my-commits)

##### Description of change

[zoslib](https://github.com/ibmruntimes/zoslib) is needed to support node.js on z/OS

### CODE REVIEW

**Comment by mhdawson** [comment]
@nodejs/node-gyp could somebody re-run the github actions?  I'm pretty sure the failures will not be related to the change as it only affects z/OS but would be good to get the CI green.

**Review by richardlau — APPROVED** [review]

**Comment by mhdawson** [comment]
I thought maybe it was just my level of access as I did not either. Is there some reasonable change we can push to retriggger. I guess we could add/remove a blank line unless somebody has better ideas.

**Comment by gengjiawen** [comment]
> I thought maybe it was just my level of access as I did not either. Is there some reasonable change we can push to retriggger. I guess we could add/remove a blank line unless somebody has better ideas.

rebase maybe a better idea.

**Comment by richardlau** [comment]
cc @zsw007

**Comment by zsw007** [comment]
> cc @zsw007

Thanks for the heads up. I went ahead and rebase this PR @mhdawson

**Pull request merged**
