### PR TITLE
docs: Update windows installation instructions in README.md

### LINKED ISSUE #2637: Windows installation: Can't find "Visual C++ build tools" workload
Trying to install on windows with the instructions from the readme.

it says:
Install Visual C++ Build Environment: [Visual Studio Build Tools](https://visualstudio.microsoft.com/thank-you-downloading-visual-studio/?sku=BuildTools) (using "Visual C++ build tools" workload)

i install visual studio build tools 2019 16.11.11, and I see a workloads tab, but none of the options are called "Visual C++ build tools"

here are the options i am given: 
setup_2022-04-02_15-19-36

am I missing something? did i install the wrong software? is it under a different name?

### PR DESCRIPTION
**Pull request by raress96**
##### Checklist

- [x] documentation is changed or added

##### Description of change
Update readme for windows installation. Fixes #2637

### CODE REVIEW

**Review by cclauss — APPROVED** [review]
RSLGTM

**Review by StefanStojanovic — CHANGES_REQUESTED** [review]
The change in the workloads section happened between VS2017 and VS2019. Here is a screenshot from VS2017 build tools installer:
image
and here are from VS2019 and VS2022:
image
image

With all of that in mind, I think both workload names should be in the README.md file and potentially another sentence telling in which versions of build tools which workload is expected.

**Comment by StefanStojanovic** [comment]
@raress96 I forgot to thank you for your effort in the previous comment. Also wanted to tell you that if you do not have time to make the change I requested, you can let me know and I'll do it.

**Comment by raress96** [comment]
Readme updated again, hopefully it is more clearer now for new users.

**Review by StefanStojanovic — APPROVED** [review]
That's much clearer, thanks @raress96!

**Pull request merged**
