### PR TITLE
doc: add Chocolatey instructions for Windows

### PR DESCRIPTION
**Pull request by kripod**
##### Checklist

- [x] documentation is changed or added
- [x] commit message follows [commit guidelines](https://github.com/nodejs/node/blob/master/doc/guides/contributing/pull-requests.md#commit-message-guidelines)

##### Description of change

Added instructions for installing Windows build tools through Chocolatey.

### CODE REVIEW

**Comment by cclauss** [comment]
I specifically removed this alternative.  Why do we want to put it back it?

Why do we want to have to support multiple ways of configuring (or misconfiguring) Windows now that Microsoft has invested heavily to put the current Python into their app store?

**Comment by cclauss** [comment]
I specifically removed this alternative installation of Python.  What is the advantage of us taking on the additional support burden two alternative ways for our users to configure (or mis-configure) Windows now that Microsoft has invested to put the current Python into the Windows AppStore?

**Comment by kripod** [comment]
For development purposes, Chocolatey is a more versatile tool, offering packages like the Visual Studio Build Tools, unlike the Microsoft Store.

**Comment by bzoz** [comment]
I'm generally +1 on this, choco is already supported by Node. But I would prefer to have this as a separate section, not interleaved with other methods. A separate list of commends, like:
```
choco install python -y
choco install visualstudio2017buildtools -y
choco install visualstudio2017-workload-vctools -y
```

Also, we should provide a link to the choco installer.

**Comment by cclauss** [comment]
I still do not see the advantage of us supporting a third party install when the operating system vendor has created a supported install.

**Comment by carlo-quinonez** [comment]
Advantage to choco vs store installs is scriptability and automation.

**Comment by cclauss** [comment]
Python is a scripting language ;-).  Like what kind of stuff?

**Comment by bzoz** [comment]
@cclauss I guess @carlo-quinonez meant that you can use choco to install python via automation scripts

**Comment by cclauss** [comment]
> install python via automation scripts

Same w/ the Microsoft version https://docs.python.org/3/using/windows.html#installing-without-ui plus the OS will know how to do upgrades.  For example, Python 3.8.3 is due this weekend.

**Comment by bzoz** [comment]
I think those commands are for the MSI installer, they don't seem to work with the Windows Store one.

**Comment by bzoz** [comment]
I'm still -1 on this in this form: https://github.com/nodejs/node-gyp/pull/2061#issuecomment-598262012

**Comment by rvagg** [comment]
I'm going with @bzoz' advice on this. This PR should be adjusted to have a separate choco section, it can't land as it is now.

**Comment by cclauss** [comment]
Perhaps choco should be added to https://docs.python.org/3/using/windows.html before it is added to this repo.

**Pull request closed without merging**
