### PR TITLE
Fix build bug in target arch config

### LINKED ISSUE #2865: Installation error caused by typo
https://github.com/nodejs/node-gyp/blob/a26494fbb8883d9ef784503979e115dec3e2791e/lib/configure.js#L271

`'<(target_arch)'` should be `'$(target_arch)'`

### PR DESCRIPTION
**Pull request by moccajoghurt**
Fixes #2865

[x] `npm install && npm test` passes

Fixed build bug in target arch config by fixing a typo.

### CODE REVIEW

**Comment by moccajoghurt** [comment]
Fixes #2866

**Review by imatlopez — APPROVED** [review]
coverage for this would be nice, seems like a rather important typo

**Comment by cclauss** [comment]
Please rebase this pull request to get fix the git conflict.

**Comment by cclauss** [comment]
Please rebase this pull request so we can get all tests to pass.

**Pull request closed without merging**
