### PR TITLE
Try python launcher when stock python is python 3.

### PR DESCRIPTION
**Pull request by bnoordhuis**
See https://github.com/nodejs/node-gyp/issues/987#issuecomment-231969392.  Add lots and lots of tests that verify all code paths.

R=@rvagg?

CI: https://ci.nodejs.org/view/All/job/nodegyp-test-commit/8/

### CODE REVIEW

**Comment by bnoordhuis** [comment]
https://ci.nodejs.org/view/All/job/nodegyp-test-commit/8/nodes=win2012r2/console - building the test add-on fails but I don't think it's related to this PR.

Let's see what a CI run of master does: https://ci.nodejs.org/view/All/job/nodegyp-test-commit/10/

**Comment by rvagg** [comment]
ack

**Comment by bnoordhuis** [comment]
Rebased, new CI: https://ci.nodejs.org/view/All/job/nodegyp-test-commit/31/

@rvagg Was your ACK an implicit LGTM or an 'I am aware this pull request exists'?

**Comment by jbergstroem** [comment]
LGTM

**Pull request merged**
