### PR TITLE
build: compile module was removed in Python 3

### PR DESCRIPTION
**Pull request by cclauss**
##### Checklist

- [ ] `npm install && npm test` passes
- [ ] tests are included 
- [ ] documentation is changed or added
- [x] commit message follows [commit guidelines](https://github.com/nodejs/node/blob/master/doc/guides/contributing/pull-requests.md#commit-message-guidelines)

##### Description of change
Our Travis CI [ModuleNotFoundError: No module named 'compiler' ](https://travis-ci.com/nodejs/node-gyp/jobs/214525323#L2600) errors are caused by the fact that [the compiler package was removed in Python 3](https://stackoverflow.com/questions/909092/why-is-the-compiler-package-discontinued-in-python-3) in favor of the __ast__ module that exists in both Python 2 and Python 3.

These changes are from https://github.com/refack/GYP/commit/f989ef9f1c41f04267eb18bed24b880ad0f8b9ec

@nodejs/python

### CODE REVIEW

**Comment by richardlau** [comment]
Tests still fail with Python 3 with:
https://travis-ci.com/nodejs/node-gyp/jobs/215440829#L3070-L3075
```console
 +gyp: Variable node -e "require('nan')" must expand to a string or list of strings; found a bytes while trying to load binding.gyp
    +gyp ERR! configure error                                                   
    +gyp ERR! stack Error: `gyp` failed with exit code: 1                       
    +gyp ERR! stack     at ChildProcess.onCpExit (/home/travis/build/nodejs/node-gyp/lib/configure.js:344:16)
    +gyp ERR! stack     at ChildProcess.emit (events.js:198:13)                 
    +gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
```

The error is coming from https://github.com/nodejs/node-gyp/blob/5bddd221b1e0a6b156d810ce497b13116182466e/gyp/pylib/gyp/input.py#L947-L962

**Comment by cclauss** [comment]
https://travis-ci.com/nodejs/node-gyp/builds/118963575 is a bit opaque to me this time.

**Comment by richardlau** [comment]
> 
> 
> https://travis-ci.com/nodejs/node-gyp/builds/118963575 is a bit opaque to me this time.

For reference:
https://travis-ci.com/nodejs/node-gyp/jobs/215572608#L1954-L1979
```console
test/test-find-python.js ............................ 24/26
  find python
  not ok should be equal
    --- wanted    
    +++ found     
    +Python 3.7.1 
    compare: ===
    at:
      line: 20
      column: 9
      file: test/test-find-python.js
    stack: |
      test/test-find-python.js:20:9
    source: |
      t.strictEqual(stdout, '')
  
  find python
  not ok expect truthy value
    at:
      line: 21
      column: 9
      file: test/test-find-python.js
    stack: |
      test/test-find-python.js:21:9
    source: |
      t.ok(/Python 2/.test(stderr))
```
also failed in https://github.com/nodejs/node-gyp/pull/1815 (https://travis-ci.com/nodejs/node-gyp/jobs/214789663#L4479-L4504) so isn't because of this PR and is unlikely to be because of anything in `gyp`. cc @joaocgreis

**Comment by joaocgreis** [comment]
This PR can land, the Python failure is unrelated.

`test-find-python` starts by looking for python as node-gyp would and confirming it is Python 2. But Python 3 is 3 and prints the version to stdout instead of stderr. I'll try to open a PR to fix this if no one beats to to it.

There are still failures in the Windows job that are not related to this.

**Comment by cclauss** [comment]
You are correct.  https://bugs.python.org/issue18338
* __python2 --version__ writes to stderr
* __python3 --version__ writes to stdout

**Comment by rvagg** [comment]
@cclauss you're good to land and you can do it manually as long as you avoid a merge commit. First I'd recommend changing the commit message because it describes _why_ not _what_. But your metadata is 👍.

Because you're not quite up to date with master, this is what I'd do to get this landed:

```sh
git checkout master
git pull origin master # replace "origin" with whatever you've called this repo
git checkout compile-module-removed-in-Python3
git rebase master # now up to date with master
git checkout master
git merge compile-module-removed-in-Python3 # should land just one commit onto master, cleanly
git push origin master # replace "origin" appropriately
```

I don't _think_ we can use `git node land` on this repo, at least it didn't seem to work with non-nodejs/node repos last time I checked. I've been doing manual metadata and landing on this repo but perhaps someone else in here has a more automatic suggestion?

**Comment by rvagg** [comment]
Oh, that `git pull origin master` might cause problems actually because I rewrote master and you may have an out of sync version of master so a `pull` might create some chaos. I think `git pull --rebase origin master` might sort that out.

I sometimes go a more explicit route when in this kind of situation just to be absolutely clear what I'm trying to achieve:

```sh
git fetch origin
git checkout origin master
git branch -D master
git checkout -b master
```

but I think `git pull --rebase origin master` will achieve the same thing in this scenario.

**Comment by rvagg** [comment]
Your metadata didn't make it to `master` so something went wrong along the way unfortunately. I've force pushed a new version of the commit with.

    PR-URL: https://github.com/nodejs/node-gyp/pull/1820
    Reviewed-By: Ben Noordhuis <info@bnoordhuis.nl>
    Reviewed-By: Rod Vagg <r@va.gg>
    Reviewed-By: Richard Lau <riclau@uk.ibm.com>

and renamed it to `build: more Python 3 compat, replace compile with ast`, bacf53df

**Comment by richardlau** [comment]
> 
> 
> Your metadata didn't make it to `master` so something went wrong along the way unfortunately. I've force pushed a new version of the commit with.
> 
> ```
> PR-URL: https://github.com/nodejs/node-gyp/pull/1820
> Reviewed-By: Ben Noordhuis <info@bnoordhuis.nl>
> Reviewed-By: Rod Vagg <r@va.gg>
> Reviewed-By: Richard Lau <riclau@uk.ibm.com>
> ```
> 
> and renamed it to `build: more Python 3 compat, replace compile with ast`, [bacf53d](https://github.com/nodejs/node-gyp/commit/bacf53dfcc0d67afb365887654b8f2446e8d05be)

I'm not in front of a computer at the moment, but it looks like this landed as a merge commit (both https://github.com/nodejs/node-gyp/commit/ef81bdbce17ae82b533250c5ae2d29ad3f93b435 and https://github.com/nodejs/node-gyp/commit/bacf53dfcc0d67afb365887654b8f2446e8d05be have two parents)?

**Comment by rvagg** [comment]
OK, I've fixed it up, reversed to the commit before and cherry-picked ef81bdb onto it then force pushed master. Thanks for picking that up @richardlau!

**Pull request merged**
