### PR TITLE
Add find python test (v2)

### PR DESCRIPTION
**Pull request by refack**
Extending #668 & #756
Solves #667, #750

### CODE REVIEW

**Comment by Trott** [comment]
Should this be rebased? Or abandoned?

**Comment by rvagg** [comment]
abandoned I guess, reopen and rebase if you want to pursue still

**Comment by cclauss** [comment]
Can we close this one?

@joaocgreis

**Comment by richardlau** [comment]
Closing due to the long period of inactivity. https://github.com/nodejs/node-gyp/blob/master/test/test-find-python.js exists.

**Pull request closed without merging**
