### PR TITLE
Modernize Python 2 code to get ready for Python 3

### PR DESCRIPTION
**Pull request by cclauss**
Similar to  #1150 

Make the minimal, safe changes required to convert the repo's code to be syntax compatible with both Python 2 and Python 3. More work will be required to complete the port to Python 3 but this is a minimal, safe first step.

* [futurize stage 1](http://python-future.org/futurize_cheatsheet.html#step-1-modern-py2-code)

##### Checklist

- [x] `npm install && npm test` passes
- [x] commit message follows [commit guidelines](https://github.com/nodejs/node/blob/master/CONTRIBUTING.md#commit-message-guidelines)

### CODE REVIEW

**Comment by bertonha** [comment]
Any news on this PR?

**Comment by Stanzilla** [comment]
any interest by the maintainers to get this done?

**Comment by cclauss** [comment]
@refack Your review please.

**Comment by cclauss** [comment]
https://bugs.chromium.org/p/gyp/issues/detail?id=36#c48 495 days until Python 2 end of life.

**Comment by cclauss** [comment]
If _anyone_ is interested in this PR then _please submit a review_:
1. Click on __Files changed__ near the top of this page
2. Click on __Review changes__
3. Select __Approve__ or __Request changes__
4. Click __Submit review__

The more approvals there are, the more confidence that Maintainers will have that these changes are worth making.

**Comment by refack** [comment]
I was waiting for the maintainer of upstream GYP to do something similar, but that probably won't happen.
@cclauss I'll be happy to review your work.

**Comment by cclauss** [comment]
What is the URL to the repo for "_upstream GYP_"?

**Comment by refack** [comment]
https://gyp.gsrc.io/
list of unmerged patches: https://chromium-review.googlesource.com/q/project:external/gyp+-status:merged
python3 patch: https://chromium-review.googlesource.com/c/external/gyp/+/479691

**Comment by cclauss** [comment]
@refack Can we _please_ proceed with the review of this PR?  Having this repo ready for the shift from legacy Python to Python will put more pressure on the maintainers of  "_upstream GYP_" to get with the times.  450 days until Python 2 EOL.

**Comment by Croydon** [comment]
I guess the idea is that [GN](https://chromium.googlesource.com/chromium/src/tools/gn/+/48062805e19b4697c5fbd926dc649c78b6aaa138/README.md) replaces GYP so we will never see major upstream GYP changes. I assume that Node needs to switch to something else entirely in the long run, but there are enough open issues for that, so we shouldn't get into this here...

**Comment by Croydon** [comment]
> GN is, originally, part of the Chromium source tree. However, this is a fork of the original GN, which has been extracted from the Chromium tree so that it may be built standalone.

It is a fork.

**Comment by cclauss** [comment]
Does upstream score better on those tests than the fork does?

**Comment by eirnym** [comment]
Please, update README as well if it works with Python 3

**Comment by cclauss** [comment]
Let’s not change README until we get more feedback from users.  No syntax errors != fully ported.

**Comment by eirnym** [comment]
I had no errors for a while by now.

**Comment by eirnym** [comment]
please, run 2to3 again

**Comment by cclauss** [comment]
2to3 is a bad idea because it often breaks Python 2 compatibility to achieve Python 3 compatibility.  This PR was created with futurize, not 2to3.

**Comment by eirnym** [comment]
I didn't said you need to apply it blindliy, but it's a good idea to highlight things.

**Comment by refack** [comment]
I'll review today.

**Comment by refack** [comment]
P.S. what I have been trying to do was revive the original GYP test suite as to have some gauge of the compatibility of this change.
If anyone can help with adding some `.gyp` based test cases, or suggesting existing addons that might be interesting to check against, that would be very helpful.

**Comment by eirnym** [comment]
a few notes on 2to3:

* `range` is usually fine even on Python2, on Python 3 it's better than xrange was.
* for each broken import or relocated module, example code below is usually used
* prefer import python3 modules first as most systems currently install python3 as default. The only difference is macOS, but most developers will install nodejs from `macports` or `homebrew`.
* if you're really struggling with syntax or importing stuff, could read source of [six](https://github.com/benjaminp/six) module. 

```python
try:
    import urllib.parse as parse
except ImportError:
    import urlparse as parse       # name have to be the same (in most cases)
```

```python
try:
    from io import StringIO
except ImportError:
    from StringIO import StringIO
```

**Comment by cclauss** [comment]
Does __gyp__ pass these two tests?
* python2 -m flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics
* python3 -m flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics

**Comment by cclauss** [comment]
For memory and efficiency reasons, converting xrange(n) to range(n) in Python 2 is not recommended unless you can guarantee n will never be huge.

**Comment by eirnym** [comment]
it's not recommended if your app is long living (not nginx gyp) and lists contain millions of records. 

For compatible code for this particular project it's more convinient to use one function everywhere.

**Comment by refack** [comment]
CI: https://ci.nodejs.org/job/nodegyp-test-pull-request/90/

**Comment by refack** [comment]
Happy futuring y'all

**Comment by eirnym** [comment]
Added another [PR](https://github.com/nodejs/node-gyp/pull/1571) with more fixes. You're welcome to review, comment and add more changes there.

**Pull request merged**
