### PR TITLE
Continuation of #1492 ("bump request to 2.87.0")

### PR DESCRIPTION
**Pull request by rvagg**
It's a shame that #1492 got mired in v0.10 support, it would have been so much easier to just ignore it! I don't even have an easy v0.10 at hand to test that it even works; although I have tried it out with ` var execFileSync = require('./process-exec-sync')` and it works.

Anyway, this pulls in #1492 with a squash and a patch to make the code consistent with the codebase, fix a bunch of nits and a bug that was causing the test to fail on my Linux machine (a problem with `'node'` not properly in PATH).

Happy to get this published asap, just need some eyes on changes first.

### CODE REVIEW

**Comment by maclover7** [comment]
CI: https://ci.nodejs.org/job/nodegyp-test-pull-request/83/

**Comment by brodybits** [comment]
Do you guys have an ETA on merge and publish?

**Comment by rvagg** [comment]
merged & published in v3.8.0

**Comment by brodybits** [comment]
Thank you @rvagg!

**Pull request closed without merging**
