### PR TITLE
Remove npm install because it uses legacy Python

### PR DESCRIPTION
**Pull request by cclauss**
Fixes https://github.com/nodejs/node-gyp/issues/1977#issuecomment-570833317 

##### Checklist

- [ ] `npm install && npm test` passes
- [ ] tests are included 
- [ ] documentation is changed or added
- [ ] commit message follows [commit guidelines](https://github.com/nodejs/node/blob/master/doc/guides/contributing/pull-requests.md#commit-message-guidelines)

### CODE REVIEW

**Comment by sam-github** [comment]
What does this fix? Is there a nodejs or https://github.com/felixrieseberg/windows-build-tools/issues bug it refers to?

The manual install of C++ build tools is pretty finicky. /cc @gireeshpunathil who has helped people work through issues with Windows setup a fair bit.

**Comment by cclauss** [comment]
Fixes: https://github.com/nodejs/node-gyp/issues/1977#issuecomment-570833317

**Comment by just-boris** [comment]
@sam-github this can serve as a relevant report in the other package: https://github.com/felixrieseberg/windows-build-tools/issues/191#issuecomment-553121195

**Comment by sam-github** [comment]
Is this obsoleted by https://github.com/felixrieseberg/windows-build-tools/pull/205 @cclauss ?

**Comment by cclauss** [comment]
That PR currently fails its tests and I do not know how to get them to pass.  If it did pass those tests and was merged then we could close this PR without merging these changes.

**Comment by richardlau** [comment]
> 
> 
> That PR currently fails its tests and I do not know how to get them to pass. If it did pass those tests and was merged then we could close this PR without merging these changes.

I think you'll need to remove the check for `' 2.'` in https://github.com/felixrieseberg/windows-build-tools/blob/b4c681c770fa429734e45600906b4271421e1328/src/utils/get-is-python-installed.ts#L13-L17

**Comment by rvagg** [comment]
I'm uncertain of the status here, it seems like it might have been made redundant? that file now checks for ` 3.` https://github.com/felixrieseberg/windows-build-tools/blob/master/src/utils/get-is-python-installed.ts#L13-L17, I suppose that's better

**Pull request closed without merging**
