### PR TITLE
deps: increase "engines" to "node" : "^12.22 || ^14.13 || >=16"

### PR DESCRIPTION
**Pull request by wraithgar**
Makes npm warn users if they are using an unsupported Node version.

##### Checklist

- [x] `npm install && npm test` passes
- [x] commit message follows [commit guidelines](https://github.com/googleapis/release-please#how-should-i-write-my-commits)

##### Description of change
Commit message follows the pattern from the last time this field was updated: https://github.com/nodejs/node-gyp/pull/2153

### CODE REVIEW

**Review by richardlau — APPROVED** [review]

**Comment by richardlau** [comment]
I think we usually treat dropping support for a version (in this case Node.js 10) as semver-major.

**Comment by wraithgar** [comment]
That was my first instinct but then I checked the git history on that line and that was not done last time.  In the cli we are treating this kind of change as a semver major, and would happily amend my commit.

The current testing matrix only includes 12.x, 14.x and 16.x which I believe only uses the latest versions in those lines.

**Comment by richardlau** [comment]
I don't feel strongly enough about this to argue either way so I'll remove the label -- this specific change is is advisory (at least for npm, I think some (all?) versions of yarn enforced engines by default). 

Given that we don't actively test against Node.js 10 we can't even say that we aren't already broken there (albeit I'm sure we'd have received plenty of reports if that been the case).

If other node-gyp maintainers disagree, feel free to put back the semver-major label.

**Comment by rvagg** [comment]
let's do semver-major `!`, it's not a big deal to bump that, releases are relatively cheap and signalling is important

@wraithgar do you have any urgency about getting a release for this out for consumption upstream?

**Comment by wraithgar** [comment]
@rvagg I'd say medium low urgency? It's mostly about allowing node-gyp to stay current w/ the latest make-fetch-happen. v10 has a couple of bug fixes in it, nothing very big (yet). It would also shrink the npm cli bundle size a bit by allowing us to dedupe make-fetch-happen up out of node-gyp.

**Pull request merged**
