### PR TITLE
node-gyp@5.1.0 Release Proposal

### PR DESCRIPTION
**Pull request by rvagg**
* [[`f37a8b40d0`](https://github.com/nodejs/node-gyp/commit/f37a8b40d0)] - **doc**: add GitHub Actions badge (#1994) (Rod Vagg) [#1994](https://github.com/nodejs/node-gyp/pull/1994)
* [[`cb3f6aae5e`](https://github.com/nodejs/node-gyp/commit/cb3f6aae5e)] - **doc**: update macOS\_Catalina.md (#1992) (James Home) [#1992](https://github.com/nodejs/node-gyp/pull/1992)
* [[`0607596a4c`](https://github.com/nodejs/node-gyp/commit/0607596a4c)] - **doc**: fix typo in README.md (#1985) (Suraneti Rodsuwan) [#1985](https://github.com/nodejs/node-gyp/pull/1985)
* [[`0d5a415a14`](https://github.com/nodejs/node-gyp/commit/0d5a415a14)] - **doc**: add travis badge (Rod Vagg) [#1971](https://github.com/nodejs/node-gyp/pull/1971)
* [[`103740cd95`](https://github.com/nodejs/node-gyp/commit/103740cd95)] - **gyp**: list(dict) so we can del dict(key) while iterating (Christian Clauss) [#2009](https://github.com/nodejs/node-gyp/pull/2009)
* [[`278dcddbdd`](https://github.com/nodejs/node-gyp/commit/278dcddbdd)] - **lib**: ignore VS instances that cause COMExceptions (Andrew Casey) [#2018](https://github.com/nodejs/node-gyp/pull/2018)
* [[`1694907bbf`](https://github.com/nodejs/node-gyp/commit/1694907bbf)] - **lib**: compatibility with semver ≥ 7 (`new` for semver.Range) (Xavier Guimard) [#2006](https://github.com/nodejs/node-gyp/pull/2006)
* [[`a3f1143514`](https://github.com/nodejs/node-gyp/commit/a3f1143514)] - **(SEMVER-MINOR)** **lib**: noproxy support, match proxy detection to `request` (Matias Lopez) [#1978](https://github.com/nodejs/node-gyp/pull/1978)
* [[`52365819c7`](https://github.com/nodejs/node-gyp/commit/52365819c7)] - **test**: remove old docker test harness (#1993) (Rod Vagg) [#1993](https://github.com/nodejs/node-gyp/pull/1993)
* [[`bc509c511d`](https://github.com/nodejs/node-gyp/commit/bc509c511d)] - **test**: add Windows to GitHub Actions testing (#1996) (Christian Clauss) [#1996](https://github.com/nodejs/node-gyp/pull/1996)
* [[`91ee26dd48`](https://github.com/nodejs/node-gyp/commit/91ee26dd48)] - **test**: fix typo in header download test (#2001) (Richard Lau) [#2001](https://github.com/nodejs/node-gyp/pull/2001)
* [[`0923f344c9`](https://github.com/nodejs/node-gyp/commit/0923f344c9)] - **test**: direct python invocation & simpler pyenv (Matias Lopez) [#1979](https://github.com/nodejs/node-gyp/pull/1979)
* [[`32c8744b34`](https://github.com/nodejs/node-gyp/commit/32c8744b34)] - **test**: fix macOS Travis on Python 2.7 & 3.7 (Christian Clauss) [#1979](https://github.com/nodejs/node-gyp/pull/1979)
* [[`fd4b1351e4`](https://github.com/nodejs/node-gyp/commit/fd4b1351e4)] - **test**: initial Github Actions with Ubuntu & macOS (Christian Clauss) [#1985](https://github.com/nodejs/node-gyp/pull/1985)

-----

This is mainly a backlog flushing exercise, as you can see, almost everything is docs or test, but there is also #1978 which hasn't yet been released on `master` so the choice is:

1) let this simmer until it's out on a v6.x release and has had time in the wild
2) remove it from this release and just flush out a doc update release
3) yolo, just release it

Will opt for 1 at the moment, it's mainly just interesting to see what the diff is. Feel free to weigh in.

### CODE REVIEW

**Comment by richardlau** [comment]
I’m okay with any of the three options but I do wonder how much in the wild exposure 6.x gets since it isn’t used by npm.

**Comment by imatlopez** [comment]
@rvagg was about to ask you if the no proxy support was making it to v5, in order to be used at our company it will need to get to node at some point and the only way is through npm which uses v5 :(

**Comment by rvagg** [comment]
@imatlopez yep, it'll go in, I just want it to bake in the wild in v6 first. That's been out for a couple of days but we should give it a couple of weeks at least to be sure (similar practice in Node.js itself for backporting is a couple of months, minimum). We have to be more careful shipping potentially breaking features in v5 since it's got a significantly larger userbase (also I don't want to be personally responsible for people screaming at npm).

**Comment by rvagg** [comment]
Speak up now if you have anything that should hold up a release.

Synced with master, updated OP and prepared package.json and CHANGELOG.md for a release tomorrow.

This puts v5 roughly in sync (minus semver-major) with v6.1.0 but also adds #2018 because that seems pretty safe and has been waiting for a new v6 release.

-----

For the record, this is the diff with master:

* [[`d1dea13fe4`](https://github.com/nodejs/node-gyp/commit/d1dea13fe4)] - **doc**: fix changelog 6.1.0 release year to be 2020 (Quentin Vernot) [#2021](https://github.com/nodejs/node-gyp/pull/2021)
* [[`a79d866ac3`](https://github.com/nodejs/node-gyp/commit/a79d866ac3)] - v6.1.0: bump version and update changelog (Rod Vagg) [#2013](https://github.com/nodejs/node-gyp/pull/2013)
* [[`9a7dd16b76`](https://github.com/nodejs/node-gyp/commit/9a7dd16b76)] - **doc**: remove backticks from Python version list (Rod Vagg) [#2011](https://github.com/nodejs/node-gyp/pull/2011)
* [[`68319a2c34`](https://github.com/nodejs/node-gyp/commit/68319a2c34)] - v6.0.1: bump version and update changelog (Rod Vagg) [#1935](https://github.com/nodejs/node-gyp/pull/1935)
* [[`1a4ff636d5`](https://github.com/nodejs/node-gyp/commit/1a4ff636d5)] - v6.0.0: bump version and update changelog (Rod Vagg) [#1892](https://github.com/nodejs/node-gyp/pull/1892)
* [[`dd0e97ef0b`](https://github.com/nodejs/node-gyp/commit/dd0e97ef0b)] - **(SEMVER-MAJOR)** **lib**: try to find `python` after `python3` (Sam Roberts) [#1907](https://github.com/nodejs/node-gyp/pull/1907)
* [[`f60ed47d14`](https://github.com/nodejs/node-gyp/commit/f60ed47d14)] - **travis**: add Python 3.5 and 3.6 tests on Linux (Christian Clauss) [#1903](https://github.com/nodejs/node-gyp/pull/1903)
* [[`c763ca1838`](https://github.com/nodejs/node-gyp/commit/c763ca1838)] - **(SEMVER-MAJOR)** **doc**: Declare that node-gyp is Python 3 compatible (cclauss) [#1811](https://github.com/nodejs/node-gyp/pull/1811)
* [[`3d1c60ab81`](https://github.com/nodejs/node-gyp/commit/3d1c60ab81)] - **(SEMVER-MAJOR)** **lib**: accept Python 3 by default (João Reis) [#1844](https://github.com/nodejs/node-gyp/pull/1844)
* [[`c6e3b65a23`](https://github.com/nodejs/node-gyp/commit/c6e3b65a23)] - **(SEMVER-MAJOR)** **lib**: raise the minimum Python version from 2.6 to 2.7 (cclauss) [#1818](https://github.com/nodejs/node-gyp/pull/1818)

**Comment by rvagg** [comment]
published v5.1.0

**Pull request closed without merging**
