### PR TITLE
Allow passing defines such as -- -DFOO=bar

### PR DESCRIPTION
**Pull request by ilatypov**
##### Checklist

- [ ] `npm install && npm test` passes
- [ ] tests are included 
- [ ] documentation is changed or added
- [ ] commit message follows [commit guidelines](https://github.com/nodejs/node/blob/master/doc/guides/contributing/pull-requests.md#commit-message-guidelines)

##### Description of change

My small change in node-pre-gyp hit a wall because `node-gyp configure .. -- -DFOO=bar` results in creating an msbuild option `/t:-DFOO=bar`, thank you very much.

https://github.com/mapbox/node-pre-gyp/pull/416

### CODE REVIEW

**Comment by ilatypov** [comment]
Sorry I do not know how to run tests.  I see some added in the change that exposed my issue.

https://github.com/nodejs/node-gyp/pull/1164

**Comment by refack** [comment]
Hello @ilatypov and thank you for the contribution.
Could you write a test for this change? An example can be:
https://github.com/nodejs/node-gyp/blob/aebdd7a710862c13592a9d2c8a28aadf661b0542/test/test-addon.js#L34-L48
(BTW: you run the test suite with a simple `npm install; npm test`)

**Comment by kewde** [comment]
Hmm, this is an issue that does not only affect the the configure options but also overloading of properties.
```
/p:FOO=bar
```
becomes
```
/t:/p:FOO=bar
```

This fix wouldn't apply in all cases :/

**Comment by rvagg** [comment]
@ilatypov would still like to pursue this? if so, please rebase to the current master and let's see if we can figure out a test for it.

**Comment by cclauss** [comment]
Too many conflicts.

**Pull request closed without merging**
