### PR TITLE
Use Travis CI to run tests on every pull request

### PR DESCRIPTION
**Pull request by cclauss**
The owner of the this repo would need to go to https://travis-ci.org/profile and flip the repository switch __on__ to enable free automated flake8 testing of each pull request.

Use flake8 to find Python syntax errors and undefined names.  There are Python 3 syntax errors and many undefined names which may raise NameError at runtime. This PR runs flake8 runs in two passes: The first looks at critical issues in stop-the-build mode and the second looks at style violations in everything-is-a-warning mode.

# Output
Python 2: https://travis-ci.com/nodejs/node/jobs/135827428#L505
Python 3: https://travis-ci.com/nodejs/node/jobs/135827419#L501

##### Checklist

- [ ] `npm install && npm test` passes
- [ ] tests are included 
- [ ] documentation is changed or added
- [ ] commit message follows [commit guidelines](https://github.com/nodejs/node/blob/master/CONTRIBUTING.md#commit-message-guidelines)

### CODE REVIEW

**Comment by cclauss** [comment]
@nodejs/gyp @bnoordhuis @maclover7 @richardlau @gibfahn @Fishrock123 @vsemozhetbyt @refack

Can we please get Travis CI tuned on for this project [like other Node projects](https://github.com/nodejs/node/blob/master/.travis.yml)?  There are existing tests and linting for JavaScript (#1497) and Python (this PR) that should be run on all pull requests before they are reviewed.

**Comment by richardlau** [comment]
This is a policy decision for @nodejs/node-gyp to take (I'm not a comitter on this project). There is an existing https://ci.nodejs.org/job/nodegyp-test-pull-request on Node.js' own CI, but I think it currently only runs tests and not linting.

**Comment by gibfahn** [comment]
>but I think it currently only runs tests and not linting.

That could be easily fixed by having the flake8 command be part of an `npm run lint` script that is run by the test command (so `npm run test` actually calls `npm run lint && npm run tap`).

I'm not a fan of this as it stands, as people will think that the test suite has been run successfully, when in fact only the linter has run. It's also a step that has to be run manually by contributors.

>Can we please get Travis CI tuned on for this project like other Node projects? 

@cclauss what exactly is your goal here? If it's to have flake8 run on test suites, then my suggestion above is the quickest way to do that.

If it's to enable travis for node-gyp, then that is a different discussion.

>There are existing tests and linting for JavaScript (#1497) and Python (this PR) that should be run on all pull requests before they are reviewed.

Why should they be run on all pull requests **before** they are reviewed? As long as they are run before the PR is landed, a linter change is unlikely to be the difference between landing and closing a PR.

**Comment by cclauss** [comment]
The entire trend of CI/CD is about using automation to test early and test often.  It questions the value of having humans review code before it has gone through some level of automated testing.

As example, let’s consider #1333 and #1334 where our code could be raising NameError exceptions at runtime.  These PRs have been open for eight months with no comment.  If flake8 was turned on then everybody who was trying to improve the code would put a 👍 on these PRs and they would have been merged months ago.

Sometime over the [next 500 days](http://pythonclock.org) this repo either needs to be ported to Python 3 or archived.  Publicly visible automated testing is recommended for efficiently doing the former.

**Comment by cclauss** [comment]
https://travis-ci.com/nodejs/node/builds/79706150

**Comment by gibfahn** [comment]
>This is PR is not attempting to be the end solution. It is merely trying to get Travis CI turned on for this repo (as it is for nodejs/node, etc.) so that we can collaborate on creating better and better tests.

Thanks for the reply, but that doesn't really answer my question.

If you want to add Travis testing to node-gyp, then Travis should be running `npm test`.

If you want to add flake8 to the test suite, it should be run as part of `npm test`, which should probably be a separate PR.

**Comment by cclauss** [comment]
Is there someone who could re-implement this PR in a way that satisfies @gibfahn's request above?

I do not understand the npm approach well enough but this PR has been open for almost a year and I believe that we would all benefit from having some basic Python linting in place.

**Comment by cclauss** [comment]
@gibfahn  npm install ; npm test in place.  @refack

**Comment by cclauss** [comment]
@gibfahn Can you or someone else please mentor me through this issue?  There are 42 open PRs and none of them go through any CI testing.  No new commit in the past week.  I opened #1337 over a year ago and one year from now Python 2 is [end of life](http://pythonclock.org).  Is it really so difficult to turn on Travis CI or any similar CI tool so that we can try to achieve Python 3 compatibility in time?

**Comment by mhdawson** [comment]
I'm thinking the current version looks reasonable to me.

I don't think we necessarily want to integrate flake8 into the npm test step as that would force everybody who wants to run npm test to install that through pip.  If we agree that makes sense we can always do it in a follow on PR.

In terms of running this on Travis before the review, we do that for Node core now, running the linter and a linux test when the PR is submitted so I think this aligns with that approach.

Given that we want to make progress on https://github.com/nodejs/TSC/issues/642, it seems important to me to start getting info on whether changes will break when node-gyp is used with Python3.

@refack @thefourtheye what do you think?

**Comment by cclauss** [comment]
@gustavosizilio See https://github.com/nodejs/node-gyp/pull/1336#issuecomment-406903438

**Comment by Flyingmana** [comment]
Are there any strong arguments against activating TravisCI?
I dont think adding this and activating needs a policy decision or similar, as its only a supporting part. It does not replace or change any of the existing processes the project has.
It also does not break anything.
And having this merged may lead to further improvements of the travis setup and reduce communication roundtrips where a maintainer is needed.

Is there anything I did miss?

//cc @refack @maclover7

**Pull request closed without merging**
