### PR TITLE
chore: remove support for EOL versions of Node.js

### PR DESCRIPTION
**Pull request by codebytere**
##### Description of change

Refs https://github.com/nodejs/node-gyp/issues/1945.

Should we also consider moving to GitHub Actions and adding specs for Node.js v14? Feel free to tell me if there's any config code specific to these EOL versions that i missed and i'll ditch it :)

##### Checklist

- [x] `npm install && npm test` passes
- [x] commit message follows [commit guidelines](https://github.com/nodejs/node/blob/master/doc/guides/contributing/pull-requests.md#commit-message-guidelines)

### CODE REVIEW

**Comment by cclauss** [comment]
Nice initiative.  +1 on switching to GitHub Actions.  Why the failing tests on Py36?

**Comment by codebytere** [comment]
@cclauss i was seeing a bunch of unexplained macOS GitHub Action runner errors earlier today on other repos too - just gave them another kick but i don't think it's related 🤔 the error showed up like this:

Screen Shot 2020-05-11 at 9 27 10 PM

which frankly is useless enough that it makes me think Actions itself was just struggling

**Comment by cclauss** [comment]
* Why not test `node_js: 14` ?
* Why not test `dist: focal` ?

**Comment by rvagg** [comment]
741ab09

+1 to Actions, and to adding 14 in there, and switching to Focal, although `ubuntu-latest` will likely get that for us anyway.

**Pull request closed without merging**
