### PR TITLE
Fixed handling of missing python on Windows. 

### PR DESCRIPTION
**Pull request by mvidmar**
##### Checklist
- [x] `npm install && npm test` passes
- [ ] tests are included
- [ ] documentation is changed or added
- [x] commit message follows [commit guidelines](https://github.com/nodejs/node/blob/master/CONTRIBUTING.md#commit-message-guidelines)

##### Description of change
configure: fixing to better handle python badVersion on windows platform

- invalid error message when python is found but is invalid version 
error returned: file not found but with valid file path which is 
confusing. error expected: invalid python version.
- in case of invalid version on guessed path (python27) it goes into
an endless loop (unlikely but an ugly error)

refs https://github.com/nodejs/node-gyp/pull/1269

### CODE REVIEW

**Comment by refack** [comment]
CI: https://ci.nodejs.org/job/nodegyp-test-pull-request/41/

**Comment by refack** [comment]
Hello @mvidmar and welcome! Thank you for the fix 🥇 

Could you describe the situation that causes the endless recursion (I want to try to design a test around that)?

Also If you could adjust the commit message to our style guide (which is roughly based on [node-core's](https://github.com/nodejs/node/blob/master/CONTRIBUTING.md#commit-message-guidelines))

**Comment by mvidmar** [comment]
Tried to fix the commit message according to the style guide, let me know if I missed something.

The loop happens on Windows when c:\Python27\python.exe is not a valid version (like I mentioned - unlikely but possible. Happened to me during trying to get an understanding of this code). The loop happens from checkPythonVersion, call to checkPythonLauncher, then guessPython, which finds the executable and then reruns checkPythonVersion. That's why I added an increase of  checkPythonLauncherDepth within guessPython so it skips the fallback to checkPythonLauncher.

I also merged our fixes in case you want to pull that instead of this fix. Since I noticed you modified some other stuff as well. Here is the merged fix with PR 1269 https://github.com/mvidmar/node-gyp/commit/9c7ad90d5caeb809580ec1620ef3853a677cb503

**Comment by rvagg** [comment]
hi @mvidmar do you still want to pursue this? if so, rebase against master and let's sort out a few style nits and get some windows people involved again

**Comment by joaocgreis** [comment]
The current code to find Python already includes both these features, I think this can be closed. If I missed something, please rebase on current master. Thanks!

**Pull request closed without merging**
