### PR TITLE
Add some Python 3 fixes to node-gyp

### PR DESCRIPTION
**Pull request by rodrigc**
This doesn't fully port node-gyp to Python 3,
but it provides some fixes which bring it in the direction which makes
doing a full port to Python 3 easier.

### CODE REVIEW

**Comment by cclauss** [comment]
@refack Your review please?

**Comment by refack** [comment]
Superseded by https://github.com/nodejs/node-gyp/pull/1335
@rodrigc thank you very much for the contribution!

**Comment by eirnym** [comment]
@refack It was too fast as syntax changes are not all changes required. 
@rodrigc I'll cherry-pick or take some of your commits.

**Comment by refack** [comment]
> @refack It was too fast as syntax changes are not all changes required.
> @rodrigc I'll cherry-pick or take some of your commits.

Since the code works (that is I'm able to test GYP with python 3.6), I'm assuiming other changes are optional, or are at edge cases.

But I'll try to rebase.

**Comment by refack** [comment]
CI: https://ci.nodejs.org/job/nodegyp-test-pull-request/92/

**Comment by refack** [comment]
@rodrigc Thank you very much!

**Pull request merged**
