### PR TITLE
gyp: update gyp-next to v0.6.0

### PR DESCRIPTION
**Pull request by ryzokuken**
Refs: https://github.com/nodejs/gyp-next/releases/tag/v0.6.0

##### Checklist

- [ ] `npm install && npm test` passes
- [ ] tests are included 
- [ ] documentation is changed or added
- [ ] commit message follows [commit guidelines](https://github.com/nodejs/node/blob/master/doc/guides/contributing/pull-requests.md#commit-message-guidelines)

##### Description of change

/cc @MylesBorins @rvagg @targos

### CODE REVIEW

**Review by MylesBorins — APPROVED** [review]
RSLGTM

**Comment by rvagg** [comment]
All those windows tests can't really be ignored and I don't know what's going on there. Can we have some (fairly urgent) windows help to figure this out please? @joaocgreis, @bzoz, anyone else?

**Comment by rvagg** [comment]
this is probably going to require someone testing it locally, the best I can see from logs is:

```
2020-10-13T19:43:58.4342460Z               gyp ERR! build error 
2020-10-13T19:43:58.4342739Z           
2020-10-13T19:43:58.4343188Z               gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual
2020-10-13T19:43:58.4343931Z               Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe` failed with exit
2020-10-13T19:43:58.4344417Z               code: 1
```

🤷 there are quite a few changes touching msvs things in this gyp update, perhaps we've touched something a bit too hard?

**Comment by cclauss** [comment]
I don’t use Windows but does this help? https://github.com/nodejs/node-gyp/issues/1663#issuecomment-707960172

**Comment by targos** [comment]
This is because of change https://github.com/nodejs/gyp-next/commit/72eddfe67f0216c3109f59efdb38dd9a2f8dddc5 and an absolute path in https://github.com/nodejs/node-gyp/blob/1e2e94d9851a1685d80d591262d0730681b5481d/addon.gypi#L77.

Confirmed locally that https://github.com/nodejs/gyp-next/pull/71 fixes it.

**Pull request closed without merging**
