### PR TITLE
feat: support IBM Open XL C/C++ & PL/I compilers on z/OS

### PR DESCRIPTION
**Pull request by gabylb**
##### Checklist
- [x] `npm install && npm test` passes
- [x] commit message follows [commit guidelines](https://github.com/googleapis/release-please#how-should-i-write-my-commits)

##### Description of change
Open XL C/C++ for z/OS (C invocation: clang, ibm-clang, or ibm-clang64) is LLVM-based, and doesn't support XL C/C++'s -q flags. Environment variable CC is set starting with Node.js v18 for z/OS which requires clang or ibm-clang64 compiler, but CC may not be set in older versions (which required njsc or xlclang), hence default to njsc to support older versions.

Also fix defines of _ALL_SOURCE and _UNIX03_SOURCE to match how they're used.

Accompanying change to `gyp/pylib/gyp/generator/make.py` now deleted from this PR per https://github.com/nodejs/node-gyp/pull/2742#pullrequestreview-1128428148 and now in https://github.com/nodejs/gyp-next/pull/178.

### CODE REVIEW

**Comment by gabylb** [comment]
Hi Richard @richardlau please review when you have a chance.

**Review by richardlau — COMMENTED** [review]
Looks okay but the changes under `gyp` should be upstreamed to https://github.com/nodejs/gyp-next.

**Comment by gabylb** [comment]
> Looks okay but the changes under `gyp` should be upstreamed to https://github.com/nodejs/gyp-next.

Done, please see https://github.com/nodejs/gyp-next/pull/178.

**Comment by gabylb** [comment]
I deleted make.py rather than reverting its change; will resolve in another PR.

**Pull request closed without merging**
