### PR TITLE
Import gyp patches from nodejs/node

### PR DESCRIPTION
**Pull request by maclover7**
##### Checklist

- [x] `npm install && npm test` passes
- [x] commit message follows [commit guidelines](https://github.com/nodejs/node/blob/master/CONTRIBUTING.md#commit-message-guidelines)

##### Description of change

This begins the process of removing `tools/gyp` from `nodejs/node`. Once this lands, a new release is published, and is upstreamed into `npm`, then `tools/gyp` can be removed from `nodejs/node`. This would result in only a single version of GYP needing to maintained by the Node.js Foundation, which would live inside `nodejs/node-gyp`.

I'm planning on opening a separate PR to get all of these on `nodejs/node-gyp@master` once this PR lands.

### GYP patches from `nodejs/node`

- https://github.com/nodejs/node/commit/625a2716c6fccfb1ff0006e11ab82bd05ab48168: applied
- https://github.com/nodejs/node/commit/5111e789e62174a72cdbe6963ed5c6e9210a7049: applied
- https://github.com/nodejs/node/commit/3debbc76057ae5df6780d4b639b67d759721c5ab: solved via https://github.com/nodejs/node-gyp/commit/b768d20f387f3518ead9bce93b1d981007d124b8
- https://github.com/nodejs/node/commit/4cc78917a88a9cf19a600aab49c7ee501378bf49: solved via https://github.com/nodejs/node-gyp/commit/625c1515f9e00a9ea933ef78c00463ffba642f19
- https://github.com/nodejs/node/commit/503916a04f067bbf20d9570a4ca126aa1c6aec66: applied
- https://github.com/nodejs/node/commit/e78a79af8cfdd73dad0e676210eef4d73b361a7a: applied
- https://github.com/nodejs/node/commit/2550152395f48ade5261dcc8d0d63e44acb89702: applied
- https://github.com/nodejs/node/commit/cbd3708c85e13b234e9ded0beaaf1780a537dc39: applied
- https://github.com/nodejs/node/commit/920c13203df434278eb7c34a485e89734a5fa62a: skipped due to revert
- https://github.com/nodejs/node/commit/fa9f31a4fda5a3782c652e56e394465805ebb50f: skipped due to revert
- https://github.com/nodejs/node/commit/3b1bf0d394811a1850bf5553d9879c82c73e9466: applied
- https://github.com/nodejs/node/commit/a9e70d7d0b50ed615428e8344d510effb6713f02: solved via https://github.com/nodejs/node-gyp/commit/40f24e4c2b851190628dcc809b340496487d7556
- https://github.com/nodejs/node/commit/51812ff12b9e10549725bcda57167148428e256c: applied

cc @nodejs/node-gyp @nodejs/gyp

### CODE REVIEW

**Comment by maclover7** [comment]
CI (https://ci.nodejs.org/job/nodegyp-test-pull-request/72/) is green besides for v0.10, which should be fixed by #1492

**Comment by maclover7** [comment]
CI (https://ci.nodejs.org/job/nodegyp-test-pull-request/75/) is green besides for v0.10, which should be fixed by #1492

**Comment by rvagg** [comment]
@maclover7 the biggest changes I see in here impact AIX and macOS, neither of which appear to be in nodegyp-test-pull-request. xcode_emulation.py is my main concern (compile_commands_json) is purely for Node's `configure` consumption). Can we get macOS into that Jenkins job?

**Comment by rvagg** [comment]
That v0.10 error got fixed in #1492 and improved in #1521, also I was on my mac messing around with this yesterday and couldn't find a problem so my comfort level has improved. Unfortunately it's edge-cases that are going to bite us since we have such a poor test suite here.

**Comment by rvagg** [comment]
merged & published in v3.8.0

**Pull request closed without merging**
