### PR TITLE
Add arm64 asm

### PR DESCRIPTION
**Pull request by jkunkee**
##### Checklist

- [x] `npm install && npm test` passes
- tests are included 
    - No GYP tests seem to be in node-gyp
- [x] commit message follows [commit guidelines](https://github.com/nodejs/node/blob/master/doc/guides/contributing/pull-requests.md#commit-message-guidelines)

##### Description of change

This is a port of https://github.com/nodejs/node/pull/26020 (see also https://github.com/refack/GYP/pull/23) to the `node-gyp` copy of GYP. It is important when building Node.js itself (V8 has ASM bits; hence the other PR) and when building native modules with ASM (fairly rare, as I understand it).

### CODE REVIEW

**Comment by jkunkee** [comment]
This is a much smaller change than https://github.com/nodejs/node-gyp/pull/1678, but they may overlap some.

**Comment by jkunkee** [comment]
This PR is redundant with upgrading node-gyp's GYP to refack/GYP.

**Comment by jkunkee** [comment]
#1678's GYP-specific parts were separated into https://github.com/refack/GYP/pull/33, then that was ported back as #1739. It might have a merge conflict with this PR, but they do not functionally overlap.

**Comment by joaocgreis** [comment]
CI: https://ci.nodejs.org/job/nodegyp-test-pull-request/126/ ✔️
ARM64 CI: https://ci.nodejs.org/view/All/job/nodegyp-test-commit-arm64/8/nodes=win10-vs2017-arm64/ ✔️
Node.js CI: https://ci.nodejs.org/view/All/job/node-test-commit-windows-arm64/16/ ✔️

Landed in https://github.com/nodejs/node-gyp/commit/721eb691cf15556cc2700eda0558d5bad5f84232

Thanks!

**Pull request closed without merging**
