### PR TITLE
feat(gyp): update gyp to v0.12.1

### PR DESCRIPTION
**Pull request by dmabupt**
Related PR: #2626

### CODE REVIEW

**Comment by dmabupt** [comment]
> LGTM. We could jump straight to gyp-next 0.12.1.

Hello @richardlau , I have updated it to v0.12.1. But there are lots of ci failures.

**Comment by dmabupt** [comment]
Duplicated PR -- https://github.com/nodejs/node/commit/b99bb57416f5eabc9d8375b93e03de21d8ed29ee
Close this.

**Comment by rvagg** [comment]
> Duplicated PR -- https://github.com/nodejs/node/commit/b99bb57416f5eabc9d8375b93e03de21d8ed29ee

but that PR is on nodejs/node, not nodejs/node-gyp, so I think we're still in need of a gyp-next upgrade here aren't we?

**Comment by kadler** [comment]
Yes, we still need this PR. @dmabupt can you please re-open?

**Review by gengjiawen — CHANGES_REQUESTED** [review]
Need to sync with `gyp-next`, not `nodejs/node` gyp folder. Currently they are not align.

**Comment by kadler** [comment]
This can be closed in favor of #2626, which now also updates gyp from gyp-next 0.13.0

**Comment by dmabupt** [comment]
Close this issue due to https://github.com/nodejs/node-gyp/pull/2626

**Pull request closed without merging**
