### PR TITLE
Removing bug from package name.

### PR DESCRIPTION
**Pull request by ussjoin**
Package name as it currently stands is a racial slur that does not
describe the project. Since the project is self-described in README.md as
"Node.js native addon build tool", this commit changes all references to
"nnabt" to remove the bug.

##### Checklist

- [x] `npm install && npm test` passes
- [x] tests are included 
- [x] documentation is changed or added
- [x] commit message follows [commit guidelines](https://github.com/nodejs/node/blob/master/doc/guides/contributing/pull-requests.md#commit-message-guidelines)

##### Description of change

Package name as it currently stands is a racial slur that does not
describe the project. Since the project is self-described in README.md as
"Node.js native addon build tool", this commit changes all references to
"nnabt" to remove the bug.

### CODE REVIEW

**Comment by rvagg** [comment]
duplicate of https://github.com/nodejs/node-gyp/issues/2168, please take discussion there, and changes to "gyp" should be directed to https://github.com/nodejs/gyp-next as we vendor in the gyp/ directory and no longer consider other edits to that directory

**Comment by ussjoin** [comment]
This is incorrect. This is a PR, not just a feature request. Please reopen.

**Comment by rvagg** [comment]
Please isolate the changes in gyp/ from this PR, we don't accept changes to that directory here. Please also use #2168 to find resolution on this question. It's an ongoing discussion and while this might be a reasonable proposal, that's all it is and #2168 should be considered the place to find consensus.

**Comment by rvagg** [comment]
And for what it's worth in terms of consensus, I'm -1 on this change.

**Comment by cclauss** [comment]
Closing.  Too many conflicts.

**Comment by ussjoin** [comment]
Not fixed. Package still racist.

**Pull request closed without merging**
