### PR TITLE
fix: wording to redirect to macOS_Catalina.md

### PR DESCRIPTION
**Pull request by nickwang14**
##### Checklist
- [x] documentation is changed or added
- [x] commit message follows [commit guidelines](https://github.com/googleapis/release-please#how-should-i-write-my-commits)

##### Description of change
Clarifies that macOS_Catalina.md is meant for any user that's upgraded beyond 10.15 and not just users that upgraded to 10.15 Catalina

### CODE REVIEW

**Comment by nickwang14** [comment]
First PR to open source ever 😅  It's pretty negligible but thought it might be helpful for others looking for node version/macOS node-gyp support

**Comment by rvagg** [comment]
👌 thanks for making this project your first @nickwang14!

I'm fine with this change, I just can't validate it. Did you use these instructions to help an upgrade to Big Sur? Were the instructions accurate?

@cclauss: any experience or thoughts on this? Should we be renaming the doc too?

**Comment by nickwang14** [comment]
Hey @rvagg! I still have a couple points pending before I can fully confirm the upgrade is working well.

To provide context, I'm trying to fix a node-gyp dependency gap when upgrading from React 16.12 to 16.14.

I am now on Monterey (Mac OS 12.1) coming from 10.12, the docs have stipulated that it's not for less than 10.15, but this is the latest update documentation that I can find 🙏 

I can document my findings and help contribute to the macOS_Updates.md when I manage to clear things up if that helps 🙏

**Comment by rvagg** [comment]
That would be wonderful @nickwang14. This doc comes from a compilation of user-supplied feedback when the big Catalina bork hit us, @cclauss did an excellent job of making sense of it all into a doc. But we're beyond that now and if we're still having similar problems then we should reflect the latest advice and consider renaming it.

**Comment by cclauss** [comment]
The chatter on our _issues_ only lasted for ~3 months when Catalina first came out.  My sense is that there is no longer much need for this content but perhaps it is still relevant for upgrades from pre-Catalina to post-Catalina.  Unclear to me but the drop in issue traffic on this topic is clear.

**Review by cclauss — APPROVED** [review]

**Pull request merged**
