### PR TITLE
feat: add support for native windows arm64 build tools

### PR DESCRIPTION
**Pull request by dennisameling**
##### Checklist

- [x] `npm install && npm test` passes
- [x] tests are included 
- [x] documentation is changed or added
- [x] commit message follows [commit guidelines](https://github.com/googleapis/release-please#how-should-i-write-my-commits)

##### Description of change

Visual Studio 2022 17.4 adds a native C++ compiler for Windows on ARM. This allows arm64 devices to leverage native build tools, leading to a 35% (or more) speed increase.

Related announcement from Microsoft: https://devblogs.microsoft.com/visualstudio/arm64-visual-studio-is-officially-here/

Building [Signal Desktop](https://github.com/signalapp/signal-desktop)'s native dependencies on a Surface Pro X (arm64 device):

```
x86 build tools (emulation): Done in 108.97s.
arm64 build tools (native): Done in 69.91s.
That's ~35.8% faster with the native tools.
```

### CODE REVIEW

**Comment by dennisameling** [comment]
@rvagg any chance this could be reviewed & merged? Now that https://github.com/nodejs/node/pull/46228 has been merged and NodeJS itself can be built _on_ arm64 (cross-compilation was already possible), having first-class support in `node-gyp` as well would be great. I just rebased the PR and updated the test with the most recent VS2022 version (17.4.33213.308). Thanks!

**Comment by richardlau** [comment]
cc @StefanStojanovic

**Review by StefanStojanovic — APPROVED** [review]
LGTM! Since GitHub actions are failing in general (not caused by this PR), I pulled this branch and ran tests locally - they passed.

**Comment by StefanStojanovic** [comment]
I'm planning to land this PR in one week (26 May), if someone has any objections to this being landed, please express them by then.

**Comment by StefanStojanovic** [comment]
@rvagg @cclauss I'm changing tests from `tap` to `mocha` in https://github.com/nodejs/node-gyp/pull/2851. Since this PR adds some tests and it's already approved, what are your thoughts on landing it so I can change those tests in my PR as well? I've already planned to land this on Friday since there were no objections, so I can do it a few days earlier.

**Comment by cclauss** [comment]
You want to merge a PR with `30 failing and 1 successful checks`?

**Comment by StefanStojanovic** [comment]
> You want to merge a PR with `30 failing and 1 successful check`?

Yes. Those tests (as is the case in other more recent PRs) are failing because the new `make-fetch-happen` version and `tap` we use not working well together (I'm working on a fix for that in https://github.com/nodejs/node-gyp/pull/2851). I reviewed this and tested it locally and all looks good.

**Review by cclauss — APPROVED** [review]

**Pull request merged**
