### PR TITLE
doc: make Windows command look more Windowsy

### PR DESCRIPTION
**Pull request by refack**
Follow up to #1152

### CODE REVIEW

**Comment by gibfahn** [comment]
Would `bat` or `cmd` make more sense [see language options](https://github.com/github/linguist/blob/master/lib/linguist/languages.yml#L348)?

**Comment by refack** [comment]
I thought about it but it's not a script it's a `ShellSession` ...

**Comment by gibfahn** [comment]
>I thought about it but it's not a script it's a ShellSession ...

Sure, but `ShellSession` [applies to bash as well](https://github.com/github/linguist/blob/master/lib/linguist/languages.yml#L4063), and is there a difference between interactively running commands and running them in a batch file (again, genuine question, there isn't in Bash, which is why we can use `bash`).

**Comment by refack** [comment]
If I had used `cmd` keywords ```cmd would have been more informative...

Yes there are differences:
1. First of all there's the prompt (`$` or `xxx>`) showing in each line, for both environments.
2. `cmd` has a weird this with variables. In an interactive session there are late revoled, and in a batch they are early resolved. so in an interactive session you would write:
```cmd
FOR %i IN (1,2,3,4) DO ECHO %i
```
but in a batch you have to escape them:
```cmd
FOR %%i IN (1,2,3,4) DO ECHO %%i
```
3. `cmd` doesn't have function so there's a weird thing about multiline statements, but I'm not getting into that...

**Comment by refack** [comment]
Not worth the bother.

**Pull request closed without merging**
